try {
(function(a){a=a.tmntag=a.tmntag||{};a._config={};a._config.GDPR_PII_CMP_LOAD_BOOST_DOMAINS=[];a._config.GDPR_MINISTUB_FOR_NON_EU_USERS_DOMAIN_LIST=[];a._config.GDPR_QUANTCAST_CONFIGURATION={};var b={Language:"en","Initial Screen Reject Button Text":"I do not accept","Initial Screen Accept Button Text":"I accept","Purpose Screen Body Text":"You can set your consent preferences and determine how you want your data to be used based on the purposes below. You may set your preferences for us independently from those of third-party partners. Each purpose has a description so that you know how we and partners use your data.",
"Vendor Screen Body Text":"You can set consent preferences for each individual third-party company below. Expand each company list item to see what purposes they use data for to help make your choices. In some cases, companies may disclose that they use your data without asking for your consent, based on their legitimate interests. You can click on their privacy policies for more information and to opt out.","Vendor Screen Accept All Button Text":"Accept all","Vendor Screen Reject All Button Text":"Reject all",
"Initial Screen Body Text":"We and our partners use technology such as cookies on our site to personalise content and ads, provide social media features, and analyse our traffic. Click below to consent to the use of this technology across the web. You can change your mind and change your consent choices at anytime by returning to this site.","Initial Screen Body Text Option":1,"Consent Scope":"service","No Option":false};a._config.GDPR_QUANTCAST_CONFIGURATION["newsarama.com"]=Object.assign({},b,{distribution:[{mode:"quantcast",
experiment:160,ratio:1},{mode:"purch",experiment:161,ratio:1}],"Publisher Name":"Newsarama","Publisher Logo":"https://dg876rejmw3ebkm51boa0sx2-wpengine.netdna-ssl.com/wp-content/uploads/2018/08/newsarama-logo.png"});a._config.GDPR_QUANTCAST_CONFIGURATION["laptopmag.com"]=Object.assign({},b,{distribution:[{mode:"quantcast",experiment:160,ratio:1},{mode:"purch",experiment:161,ratio:1}],"Publisher Name":"Laptop","Publisher Logo":"https://dg876rejmw3ebkm51boa0sx2-wpengine.netdna-ssl.com/wp-content/uploads/2018/08/laptopmag-logo.png"})})(window);
} catch (e) {
console.error(e);
}
!function(d,g){for(var a in g)d[a]=g[a]}(window,function(d){function g(b){if(a[b])return a[b].exports;var f=a[b]={i:b,l:!1,exports:{}};return d[b].call(f.exports,f,f.exports,g),f.l=!0,f.exports}var a={};return g.m=d,g.c=a,g.d=function(a,f,u){g.o(a,f)||Object.defineProperty(a,f,{enumerable:!0,get:u})},g.r=function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(a,"__esModule",{value:!0})},g.t=function(a,f){if(1&f&&
(a=g(a)),8&f)return a;if(4&f&&"object"==typeof a&&a&&a.__esModule)return a;var b=Object.create(null);if(g.r(b),Object.defineProperty(b,"default",{enumerable:!0,value:a}),2&f&&"string"!=typeof a)for(var r in a)g.d(b,r,function(b){return a[b]}.bind(null,r));return b},g.n=function(a){var b=a&&a.__esModule?function(){return a.default}:function(){return a};return g.d(b,"a",b),b},g.o=function(a,f){return Object.prototype.hasOwnProperty.call(a,f)},g.p="",g(g.s=28)}([function(d,g,a){function b(a){return window.tmntag.markupsInfo&&
window.tmntag.markupsInfo[a]&&window.tmntag.markupsInfo[a].rtbSold}function f(a){return window.tmntag.markupsInfo&&window.tmntag.markupsInfo[a]&&window.tmntag.markupsInfo[a].bidderid}function u(a){if(window.tmntag_getAdunitFromCache)return(a=window.tmntag_getAdunitFromCache(a))&&a.dfpCampaignId;return null}function r(a){if(window.tmntag_getAdunitFromCache)return(a=window.tmntag_getAdunitFromCache(a))&&a.dfpLineItemId;return null}function m(a,b){window.tmntag.refresh&&window.tmntag.refresh(a,void 0,
String(b.refreshCount-1))}function h(a,b){return!!window.tmntag&&(void 0===a?window.tmntag.adparams:void 0===b?window.tmntag.adparams&&window.tmntag.adparams[a]:window.tmntag.adparams&&window.tmntag.adparams[a]&&window.tmntag.adparams[a][b])}a.d(g,"a",function(){return b}),a.d(g,"d",function(){return f}),a.d(g,"f",function(){return u}),a.d(g,"e",function(){return r}),a.d(g,"c",function(){return m}),a.d(g,"g",function(){return h}),a.d(g,"b",function(){return q});var q=function(a,b,c){var n=2<arguments.length&&
void 0!==c?c:{};return a.reduce(function(a,c){return-1!==b.indexOf(c[0])&&(a[c[0]]=c[1]),a},n)}},function(d,g){d.exports=function(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}},function(d,g){function a(a,f){for(var b=0;b<f.length;b++){var r=f[b];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(a,r.key,r)}}d.exports=function(b,f,d){return f&&a(b.prototype,f),d&&a(b,d),b}},function(d,g,a){a.d(g,"d",function(){return m}),
a.d(g,"c",function(){return h}),a.d(g,"e",function(){return q}),a.d(g,"b",function(){return c}),a.d(g,"a",function(){return n});var b=a(5),f=a(4),u=a(9),r="allowed",m=function(a){r=a},h=function(){return r},q=function(a){return new Promise(function(b){!function z(){"function"==typeof window.__cmp?("function"==typeof a&&a(),b()):window.setTimeout(z,100)}()})},t=function(){for(var a=arguments.length,b=new Array(a),c=0;c<a;c++)b[c]=arguments[c];return new Promise(function(a){var c;(c=window).__cmp.apply(c,
b.concat([function(c){a(c)}]))})},l=function(a){return function(){return t("getVendorConsents",a?[a]:[])}},c=function(){return function(){return t("getConsentData",null)}},n=function(a,c){if(Object(u.d)())q().then(l(a)).then(function(b){var n=b.gdprApplies;b=b.vendorConsents;return n?b&&b[a]?c():null:c()});else switch(r){case "blocked":return null;case "allowed":return c();case "managed":var n=Object(f.a)("guitarworld.com|loudersound.com|phonandroid.com|frandroid.com|generation-nt.com|gamergen.com|numerama.com|driverscloud.com|hitek.fr|tomsguide.fr|tomshardware.fr|creativebloq.com|howtogeek.com|androidcentral.com|crackberry.com|imore.com|modmy.com|windowscentral.com");if(Object(b.a)(n))return c();q().then(function(a){return function(){return t("addEventListener",
a)}}("cmpReady")).then(l(a)).then(function(b){return(b=b.vendorConsents)&&b[a]?c():null});break;default:return c()}return null}},function(d,g,a){a.d(g,"a",function(){return b});var b=function(a){return a&&0!==a.indexOf("$")?a.split("|"):[]}},function(d,g,a){function b(){return Boolean((0<arguments.length&&void 0!==arguments[0]?arguments[0]:[]).find(function(a){return-1!==document.location.hostname.indexOf(a)}))}a.d(g,"a",function(){return b})},,function(d,g,a){function b(a){var b=a.getBoundingClientRect();
a=b.top;var c=b.right,n=b.bottom,l=b.left,m=.5*b.width,b=.5*b.height;return b<n&&window.innerWidth-l>m&&window.innerHeight-a>b&&m<c}d=a(1);var f=a.n(d);d=a(2);var u=a.n(d),r=function(){function a(b){f()(this,a),this.elements=b,this.current=[],this.handlers={enter:[],exit:[]}}return u()(a,[{key:"check",value:function(){var a=this;return this.elements.forEach(function(c){var n=b(c),l=a.current.indexOf(c),m=-1<l,h=!n&&m;n&&!m&&(a.current.push(c),a.emit("enter",c)),h&&(a.current.splice(l,1),a.emit("exit",
c))},this),this}},{key:"on",value:function(a,b){return this.handlers[a].push(b),this}},{key:"emit",value:function(a,b){for(var c=this.handlers[a].length;-1<--c;)this.handlers[a][c](b);return this}}]),a}(),m,h,q,t,l,c,n,K,y={history:[]},D=(m=function(){y.history.forEach(function(a){y[a].check()})},h=100,c=null,n=0,K=function(){n=new Date,c=null,l=m.apply(q,t),c||(q=t=null)},function(){var a=new Date,b=h-(a-n);return q=this,t=arguments,b<=0||h<b?(c&&(clearTimeout(c),c=null),n=a,l=m.apply(q,t),c||(q=
t=null)):c=c||setTimeout(K,b),l});["scroll","resize","load"].forEach(function(a){window.addEventListener(a,D)}),window.MutationObserver&&window.addEventListener("DOMContentLoaded",function(){(new MutationObserver(D)).observe(document.body,{attributes:!0,childList:!0,subtree:!0})});a=function(a){if("string"!=typeof a)return null;var b=[].slice.call(document.querySelectorAll(a));return-1<y.history.indexOf(a)?y[a].elements=b:(y[a]=new r(b),y.history.push(a)),y[a]};a.is=b,g.a=a},function(d,g){function a(b){return(a=
"function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a})(b)}function b(f){return"function"==typeof Symbol&&"symbol"===a(Symbol.iterator)?d.exports=b=function(b){return a(b)}:d.exports=b=function(b){return b&&"function"==typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":a(b)},b(f)}d.exports=b},function(d,g,a){a.d(g,"b",function(){return h}),
a.d(g,"d",function(){return t}),a.d(g,"c",function(){return l});d=a(23);var b=a.n(d),f=a(4),u=a(5),r=a(10),m=function(){var a=window.tmntag.config.get("GDPR_QUANTCAST_CONFIGURATION")||{},b=Object.keys(a).find(function(a){return-1!==document.location.hostname.indexOf(a)});return b?a[b]:null};g.a=function(){function a(a){var b,c="string"==typeof a.data;if((b=c?-1!==a.data.indexOf("__cmpCall")?JSON.parse(a.data):{}:a.data).__cmpCall){var n=b.__cmpCall;window.__cmp(n.command,n.parameter,function(b,l){b=
{__cmpReturn:{returnValue:b,success:l,callId:n.callId}};a.source.postMessage(c?JSON.stringify(b):b,"*")})}}var b=document.createElement("script");b.src="https://quantcast.mgr.consensu.org/cmp.js",b.async=!0,b.type="text/javascript";var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(b,l);!function D(){if(!window.frames.__cmpLocator)if(document.body){var a=document.body,b=document.createElement("iframe");b.style="display:none",b.name="__cmpLocator",a.appendChild(b)}else setTimeout(D,
5)}(),window.__cmp=function(a){var b=arguments;if(!b.length)return window.__cmp.a;if("ping"===b[0])b[2]({gdprAppliesGlobally:!1,cmpLoaded:!1},!0);else{if("__cmp"===a)return!1;void 0===window.__cmp.a&&(window.__cmp.a=[]),window.__cmp.a.push([].slice.apply(b))}},window.__cmp.gdprAppliesGlobally=!1,window.__cmp.msgHandler=a,window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent("onmessage",a);(b=m())?window.__cmp("init",b):window.__cmp("init",{Language:"en","Initial Screen Reject Button Text":"I do not accept",
"Initial Screen Accept Button Text":"I accept","Purpose Screen Body Text":"You can set your consent preferences and determine how you want your data to be used based on the purposes below. You may set your preferences for us independently from those of third-party partners. Each purpose has a description so that you know how we and partners use your data.","Vendor Screen Body Text":"You can set consent preferences for each individual third-party company below. Expand each company list item to see what purposes they use data for to help make your choices. In some cases, companies may disclose that they use your data without asking for your consent, based on their legitimate interests. You can click on their privacy policies for more information and to opt out.",
"Vendor Screen Accept All Button Text":"Accept all","Vendor Screen Reject All Button Text":"Reject all","Initial Screen Body Text":"We and our partners use technology such as cookies on our site to personalise content and ads, provide social media features, and analyse our traffic. Click below to consent to the use of this technology across the web. You can change your mind and change your consent choices at anytime by returning to this site.","Initial Screen Body Text Option":1,"Publisher Name":"Newsarama",
"Publisher Logo":"https://www.dropbox.com/s/31kj7zycqanrcko/Capture%20d%E2%80%99%C3%A9cran%202019-06-11%20%C3%A0%2014.23.29.png?raw=1","Consent Scope":"service","No Option":!1});b=document.createElement("style");b.innerText="\n  .qc-cmp-button {\n    background-color: #1a98ee !important;\n    border-color: #1a98ee !important;\n  }\n  .qc-cmp-button:hover {\n    background-color: transparent !important;\n    border-color: #1a98ee !important;\n  }\n  .qc-cmp-alt-action,\n  .qc-cmp-link {\n    color: #1a98ee !important;\n  }\n  .qc-cmp-button {\n    color: #000000 !important;\n  }\n  ",
document.head.appendChild(b)};var h=function(){return Object(u.a)(Object(f.a)("newsarama.com|laptopmag.com"))||-1!==document.location.search.indexOf("cmp=quantcast")},q=function(){var a=r.a.get("cmp_choice");a||(a=function(){var a,c=m().distribution,c=(a=[]).concat.apply(a,b()(c.map(function(a){return Array(a.ratio).fill(a)})));return c[Math.floor(Math.random()*c.length)]}().mode,r.a.set("cmp_choice",a));return a},t=function(){return!!h()&&"quantcast"===q()},l=function(){if(h()){var a=
function(){var a=m().distribution;if(!a)return null;var b=q();return a.find(function(a){return a.mode===b})}();a.experiment&&window.googletag.pubads().getSlots().forEach(function(b){return b.setTargeting("experiment",a.experiment)})}}},function(d,g,a){d={get:function(a){a=("; "+document.cookie).split("; "+a+"=");if(2===a.length)return a.pop().split(";").shift()},getAll:function(){return document.cookie.split("; ").reduce(function(a,f){var b=f.indexOf("=");return a[f.substr(0,b)]=f.substr(b+1),a},
{})},set:function(a,f,d,r){var b=new Date;b.setTime(b.getTime()+1E3*d);a=["".concat(a,"=").concat(f),"expires=".concat(b.toUTCString()),"path=/"];r&&a.push("domain=".concat(r)),document.cookie=a.join(";")}};g.a=d},function(d,g,a){d=a(1);var b=a.n(d);d=a(2);var f=a.n(d),u=function(){function a(m){b()(this,a),this.name=m,this.callbacks=[]}return f()(a,[{key:"registerCallback",value:function(a){this.callbacks.push(a)}}]),a}();a=function(){function a(){b()(this,a),this.events={}}return f()(a,[{key:"dispatchEvent",
value:function(a,b){if("string"!=typeof a)throw new Error('"eventName" must be a string');this.events[a]&&this.events[a].callbacks.forEach(function(a){a(b)})}},{key:"addEventListener",value:function(a,b){if("string"!=typeof a)throw new Error('"eventName" must be a string');if("function"!=typeof b)throw new Error('"callback" must be a function');this.events[a]=this.events[a]||new u(a),this.events[a].registerCallback(b)}},{key:"removeEventListener",value:function(a,b){if("string"!=typeof a)throw new Error('"eventName" must be a string');
if("function"!=typeof b)throw new Error('"callback" must be a function');this.events[a]&&-1!==this.events[a].callbacks.indexOf(b)&&this.events[a].callbacks.splice(this.events[a].callbacks.indexOf(b),1)}}]),a}();g.a=new a},,function(d,g,a){var b=a(16),f=a(17),u=a(18);d.exports=function(a,d){return b(a)||f(a,d)||u()}},,function(d,g,a){function b(a){var b=window.purchs2s.dfpInfos;if(b&&b[a]&&b[a].dfpLineItemId){var c=b[a].dfpLineItemId;return Object.entries(b).filter(function(a){a=D()(a,2);a[0];return a[1].dfpLineItemId===
c}).map(function(a){a=D()(a,2);var b=a[0];a[1];return b})}return[]}function f(){return window.purchs2s?function(a){return window.purchs2s.bidResponse&&window.purchs2s.bidResponse.bids&&window.purchs2s.bidResponse.bids.find(function(b){return b.divid===a})&&window.purchs2s.bidResponse.bids.find(function(b){return b.divid===a}).rtbSold}.apply(void 0,arguments):y.a.apply(void 0,arguments)}function u(){return window.purchs2s?function(a){return window.purchs2s.bidResponse&&window.purchs2s.bidResponse.bids&&
window.purchs2s.bidResponse.bids.find(function(b){return b.divid===a})&&window.purchs2s.bidResponse.bids.find(function(b){return b.divid===a}).bdrid}.apply(void 0,arguments):y.d.apply(void 0,arguments)}function r(){return window.purchs2s?function(a){return window.purchs2s.dfpInfos&&window.purchs2s.dfpInfos[a]&&window.purchs2s.dfpInfos[a].dfpCampaignId}.apply(void 0,arguments):y.f.apply(void 0,arguments)}function m(){return window.purchs2s?function(a){return window.purchs2s.dfpInfos&&window.purchs2s.dfpInfos[a]&&
window.purchs2s.dfpInfos[a].dfpLineItemId}.apply(void 0,arguments):y.e.apply(void 0,arguments)}function h(){return window.purchs2s?function(a){if(window.purchs2s.refresh&&(window.purchs2s.refresh(a),window.purchs2s.disablePurchS2SDFPRefresh&&window.headertag)){var b=window.googletag.pubads().getSlots().filter(function(b){return b.getSlotElementId()===a});window.headertag.cmd.push(function(){window.headertag.refresh(b)})}}.apply(void 0,arguments):y.c.apply(void 0,arguments)}function q(){return!!window.purchs2s&&
function(a){return 3<=b(a).length}.apply(void 0,arguments)}function t(a){v("Reinitializing ".concat(E(M)," timer"),a.id),a.autorefreshTimers&&a.autorefreshTimers.stop(),a.autorefreshTimers=new B(M,F,a.id,function(){!function(a){var c=document.querySelector("#".concat(a));if(c.refreshCount++,delete c.viewableTimer,delete c.canRefresh,!function(a,c){if(C<c)return v("Enough refreshes, this one was the last one",a),!1;if(q(a))return v("Currently displaying a roadblock so we don't refresh",a),v("Adunits used by the roadblock: ".concat(function(){return window.purchs2s?
b.apply(void 0,arguments):[]}(a).join(", "))),!1;if(!f(a)){if(!N)return v("Can't refresh, ADX refresh is disabled",a),!1;c=r(a);var n=m(a);return c?L.includes(c)?(v("Can't refresh, ad has not been served by RAMP and its DFP Order ID (".concat(c,") is in the unrefreshable DFP Orders list"),a),!1):G.includes(n)?(v("Can't refresh, ad has not been served by RAMP and its Line Item ID (".concat(n,") is in the unrefreshable DFP LineItems list"),a),!1):(v("Can refresh, ad has not been served by RAMP, but its DFP Order ID (".concat(c,
") and its DFP Line Item ID (").concat(n,") are not in the unrefreshable DFP Orders and DFP LineItems lists"),a),!0):(v("Can't refresh, ad has not been served by RAMP and its DFP Order ID is null",a),!1)}c=u(a);return v("Bidder ID: ".concat(c||"null"),a),-1!==x.indexOf(c)||(v("Can't refresh, it's currently displaying an ad from bidder ".concat(c),a),!1)}(a,c.refreshCount))return c.refreshable=!1;v("Refreshing (refresh #".concat(c.refreshCount,")"),a),h(a,c),t(c)}(a.id)}),K.a.is(a)&&Object(K.a)("#".concat(a.id)).emit("enter",
a)}function l(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};M=b.refreshDelay||3E4,F=b.viewableDelay||1E4,C=b.limit||4,x=b.refreshableBiddersIds||[],L=b.unrefreshableOrders||[],G=b.unrefreshableLineItems||[],N=b.ADXRefreshEnabled||!1,(v=b.debug?v:function(){})("Configuration:"),v("Refresh delay: ".concat(E(M))),v("Viewable delay: ".concat(E(F))),v("Refresh limit: ".concat(C)),v("Refreshable bidders: ".concat(x.join(", "))),v("ADX refresh enabled: ".concat(N)),v("Unrefreshable Orders: ".concat(L.join(", "))),
v("Unrefreshable LineItems: ".concat(G.join(", "))),v("Adunits selected for autorefresh: ".concat(a.join(", "))),a.forEach(function(a){var b="#".concat(a),c=document.querySelector(b);c&&(c.refreshCount=c.refreshCount||0,c.refreshable=!0,Object(K.a)(b).on("enter",function(b){b.autorefreshTimers.entersViewport(),v("Adunit just entered viewport. ".concat(E(b.autorefreshTimers.remaining()[0])," left in refresh timer. ").concat(E(b.autorefreshTimers.remaining()[1])," left in viewability timer."),a)}).on("exit",
function(b){b.autorefreshTimers.leavesViewport(),v("Adunit just left viewport. ".concat(E(b.autorefreshTimers.remaining()[0])," left in refresh timer. ").concat(E(b.autorefreshTimers.remaining()[1])," left in viewability timer."),a)}),t(c))}),H()}d=a(1);var c=a.n(d);d=a(2);var n=a.n(d),K=a(7),y=a(0);d=a(13);var D=a.n(d),z=a(11);a.d(g,"a",function(){return l});var M,F,x,C,L,G,N,v=function(a,b){var c=b?"[".concat(b,"] "):"";b=b?"text-transform: uppercase; font-size: smaller; font-weight: bold; color: black; background-color: orange; padding: .2em 0em; border-radius: 3px; margin: 0 3px":
"";console.log("%cAutorefresh [".concat((new Date).toLocaleTimeString(),"]%c ").concat(c,"%c").concat(a),"text-transform: uppercase; font-size: smaller; font-weight: bold; color: white; background-color: black; padding: .2em .5em; border-radius: 3px",b,"")},E=function(a){return"".concat(a/1E3,"s")},O=function(){function a(b,n){c()(this,a),this.remainingTime=n,this.paused=!1,this.callback=b,this.resume()}return n()(a,[{key:"pause",value:function(){window.clearTimeout(this.timerId),this.remainingTime-=
new Date-this.start,this.paused=!0}},{key:"resume",value:function(){this.start=new Date,window.clearTimeout(this.timerId),this.timerId=window.setTimeout(this.callback,this.remainingTime),this.paused=!1}},{key:"remaining",value:function(){return this.paused?Math.max(0,this.remainingTime):Math.max(0,this.remainingTime-(new Date-this.start))}}]),a}(),B=function(){function a(b,n,l,w){var t=this;c()(this,a),this.inView=!1,this.viewableTimerFinished=!1,this.refreshTimerFinished=!1,this.refreshDelay=b,this.viewableDelay=
n,this.divId=l,this.callback=w,this.refreshTimer=new O(function(){t.refreshTimerFinished=!0,t.executeCallback()},this.refreshDelay)}return n()(a,[{key:"entersViewport",value:function(){var a=this;return this.inView=!0,this.viewableTimerFinished?this.executeCallback():(this.viewableTimer?this.viewableTimer.resume():this.viewableTimer=new O(function(){a.viewableTimerFinished=!0,a.executeCallback()},this.viewableDelay),null)}},{key:"leavesViewport",value:function(){this.inView=!1,this.viewableTimer.pause()}},
{key:"executeCallback",value:function(){this.refreshTimerFinished&&this.viewableTimerFinished&&this.inView&&(v("adunit has spend ".concat(E(this.viewableDelay)," in view and ").concat(E(this.refreshDelay)," timer is finished and element is in view, we can try to refresh it"),this.divId),this.callback())}},{key:"stop",value:function(){this.refreshTimer&&this.refreshTimer.pause(),this.viewableTimer&&this.viewableTimer.pause()}},{key:"remaining",value:function(){return[this.refreshTimer.remaining(),
this.viewableTimer.remaining()]}}]),a}(),I,J,H=(J=!(I=function(){z.a.addEventListener("refresh",function(a){a&&a.divIds&&!a.trn&&a.divIds.forEach(function(a){a=document.getElementById(a);a.autorefreshTimers&&(a.autorefreshTimers.stop(),t(a))})})}),function(){var a;return J||(a=I.apply(void 0,arguments)),J=!0,a})},function(d,g){d.exports=function(a){if(Array.isArray(a))return a}},function(d,g){d.exports=function(a,b){var f=[],d=!0,g=!1,m=void 0;try{for(var h,q=a[Symbol.iterator]();!(d=(h=q.next()).done)&&
(f.push(h.value),!b||f.length!==b);d=!0);}catch(t){g=!0,m=t}finally{try{d||null==q.return||q.return()}finally{if(g)throw m;}}return f}},function(d,g){d.exports=function(){throw new TypeError("Invalid attempt to destructure non-iterable instance");}},function(d,g,a){a.d(g,"b",function(){return f}),a.d(g,"a",function(){return u});var b=function(a){var b=[];return a.forEach(function(a){window.tmntag.slots[a]&&b.push(window.tmntag.slots[a])}),b},f=function(a,d,f){var g=function(a,b){var c=a.account;if(c)if((c=
c.split("/"))&&0<c.length){var n=c.reverse()[0];if(0<n.indexOf("-")){if((n=n.split("-"))&&0<n.length)for(var l=0;l<n.length;l++){var f=n[l];if(0==f.indexOf("p")){f=f.substring(1);isNaN(f)||(f=1*f+(b+1),n[l]="p"+f)}}c[0]=n.join("-"),a.account=c.reverse().join("/")}}},t=function(a){var b=a.targeting||{},c;for(c in b)b.hasOwnProperty(c)&&"_p"===c&&b[c]&&(a.targeting[c]=1*b[c]+1)};if(!("JSON"in window))return!1;var l=[];if(a.forEach(function(a){var b=a.divId;a=a.cloneDivId;var c=function(a,b){var c=window.tmntagCache.filter(function(b){return b.div&&
0===b.div.indexOf(a)});return 0!=c.length&&(b&&b.resetPosition?c[0]:c[c.length-1])}(b,f);if(!c)return!1;for(var h=a.constructor===Array?a:[a],m=[],r=0,u=0;u<h.length;u++){var q=void 0;a=h[u];try{q=JSON.parse(JSON.stringify(c))}catch(C){return!1}if(q.div=a,q.targeting=q.targeting||{},d)for(var x in d)d.hasOwnProperty(x)&&d[x]&&(q.targeting[x]=d[x]);window.tmntag.adparams=window.tmntag.adparams||{},window.tmntag.adparams[a]=window.tmntag.adparams[b],f&&f.disableIncrementAccountPosition||(f&&!f.resetPosition||
0<u)&&g(q,r++),f&&f.disableIncrementPosition||c.disableIncrementPosition||t(q),window.tmntag.adunit(q),c.adunitRule&&window.tmntag.getAdParameters(b)&&"true"===window.tmntag.getAdParameters(b).on_clone_execute_preadunitrender&&c.adunitRule.apply(null,[a]);q=window.tmntag_defineSlot(a,q.targeting);l.push(a),m.push(q)}window.tmntag.events.dispatchEvent("adunitCloned",{originalDivId:b,clonedDivIds:l})}),f&&f.disableRefreshRamp)window.googletag.cmd.push(function(){for(var a=0;a<l.length;a++)window.googletag.display(l[a]);
window.tmntag_initialLoadDisabledMode&&window.googletag.pubads().refresh(b(l))});else{a=f&&f.pageUrl||"";window.tmntag.start(!0,l,function(){window.googletag.cmd.push(function(){for(var a=0;a<l.length;a++)window.googletag.display(l[a]);window.tmntag_initialLoadDisabledMode&&window.googletag.pubads().refresh(b(l))})},null,null,null,!0,a)}},u=function(a,b,d,g){return f([{divId:a,cloneDivId:b}],d,g)}},function(d,g,a){d.exports=a(32)},function(d,g,a){var b=a(0);g.a=function(a){var f=document.getElementById(a);
return!(!f||"true"!==Object(b.g)(a,"sticky"))&&(f.style.position="sticky",f.style.top="0",f.parentNode.style.height="100%",!0)}},function(d,g,a){var b=a(0);g.a=function(a){if("true"!==Object(b.g)(a,"anchor"))return!1;var f=document.getElementById.bind(document),d=window.GUMGUM;d&&d.isad&&d.isad.closeAd();var g=f(a);if(function(a){var b=window.tmntag;return b&&b.markupsInfo&&b.markupsInfo[a]&&"48"===b.markupsInfo[a].bidderid&&b.markupsInfo[a].rtbSold}(a))return g&&(g.style.display="none"),!0;if(!g)return console.error("-- RAMP --- Element Not Found in DOM ".concat(a)),
!1;g.classList.add("purch-anchor-adunit");var h,q=Object(b.g)(a,"anchor.bottomOffset")||0;if(d=Object(b.g)(a,"anchor_cookieBannerSelector")){var t=document.querySelector(d);if(t)h=t.getBoundingClientRect().height,q+=h,(new MutationObserver(function(a){a.forEach(function(a){a=Array.prototype.slice.call(a.removedNodes);(-1<a.indexOf(t)||a.find(function(a){return a.contains(t)}))&&(g.style.bottom="".concat(q-h,"px"))})})).observe(document.body,{subtree:!0,childList:!0})}Object.assign(g.style,{position:"fixed",
bottom:"".concat(q,"px"),zIndex:g.style.zIndex||"1000",display:"block",width:"100%",left:0,textAlign:"center",backgroundColor:"rgba(255, 255, 255, .8)",boxShadow:"0 -1px 1px 0 rgba(0, 0, 0, .2)",paddingTop:"5px"}),function(){var a=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream,b=window.devicePixelRatio||1,l=window.screen.width*b,b=window.screen.height*b;return a&&(1125===l&&2436===b||828===l&&1792===b||1242===l&&2688===b)}()&&q<15&&(g.style.bottom="15px");var d="tmn-mobile-anchor-close-button-link-id_".concat(a),
l=f(d);return l||((l=document.createElement("a")).addEventListener("click",function(){f(a).style.display="none"}),l.innerHTML="&times;",l.id=d,Object.assign(l.style,{fontFamily:"sans-serif",color:"#b2b2b2",backgroundColor:"rgba(255, 255, 255, .5)",textDecoration:"none",borderRadius:"50%",position:"absolute",right:"5px",textAlign:"center",display:"none",width:"20px",height:"20px",lineHeight:"20px",border:"1px solid #b2b2b2",top:"8px"})),g.appendChild(l),setTimeout(function(){l.style.display="inline-block"},
3E3),!0}},function(d,g,a){var b=a(29),f=a(30),u=a(31);d.exports=function(a){return b(a)||f(a)||u()}},function(d,g,a){a.d(g,"a",function(){return q});d=a(1);var b=a.n(d);d=a(2);var f=a.n(d),u=a(10),r=a(5),m=a(3),h=a(4),q=function(){function a(){b()(this,a),this.cookiesMap=u.a.getAll()}return f()(a,[{key:"create",value:function(a,b,d,f,g){var c=this,l="usp.".concat(a);this.cookiesMap[l]||Object(m.a)(b,function(){var a=Object(h.a)(d);Object(r.a)(a)===f&&function(a,b){a&&-1!==["IFRAME","IMG","SCRIPT"].indexOf(a.tagName)?
(a.addEventListener("load",function(){return b(a)}),a.addEventListener("error",function(){return b(a)})):b(a)}(g(),function(){return c.refreshCookie(l)})})}},{key:"refreshCookie",value:function(a){var b;2<document.location.hostname.split(".").length&&(b=document.location.hostname.split(".").slice(1).join(".")),u.a.set(a,1,"604800",b),this.cookiesMap[a]=1}}]),a}()},function(d,g){function a(a,d,g,r,m,h,q){try{var b=a[h](q),l=b.value}catch(c){return void g(c)}b.done?
d(l):Promise.resolve(l).then(r,m)}d.exports=function(b){return function(){var d=this,g=arguments;return new Promise(function(f,m){function h(b){a(t,f,m,h,q,"next",b)}function q(b){a(t,f,m,h,q,"throw",b)}var t=b.apply(d,g);h(void 0)})}}},function(d,g,a){var b=function(a,b){return Promise.race([new Promise(a),new Promise(function(a){window.setTimeout(a,b)})])};d=a(20);var f=a.n(d);d=a(25);var u=a.n(d),r={init:function(){var a=u()(f.a.mark(function c(a,b){return f.a.wrap(function(c){for(;;)switch(c.prev=
c.next){case 0:return c.next=2,new Promise(function(a){var b=document.createElement("script");b.src="https://static.adsafeprotected.com/vans-adapter-google-ima.js",b.addEventListener("load",a),document.body.appendChild(b)});case 2:a.on("adsManager",function(a){var c=a.adsManager;a=a.videoElement;var d={anId:"923193",campId:"640x480",chanId:b};window.googleImaVansAdapter.init(window.google,c,a,d)});case 3:case "end":return c.stop()}},c)}));return function(b,d){return a.apply(this,arguments)}}()},m=
function(a,b,c){return c=c||{},a.reduce(function(a,c){return-1!==b.indexOf(c[0])&&(a[c[0]]=c[1]),a},c)},h={settings:{},status:{},logError:function(a){if(h.triggerErrorEventEnabled){var b={};tmntag.pubtargets&&(b=m(tmntag.pubtargets,["_rid"],b)),window.tmntag_triggerEvent("VE",{crid:a.code,ad:encodeURIComponent(a.tag),id:b._rid})}console.log("-RAMP VIDEO- Error",a)}},q=function(a,b,c){b={};tmntag.markupsInfo&&tmntag.markupsInfo[c]&&(b.bidderid=tmntag.markupsInfo[c].bidderid,b.adomain=tmntag.markupsInfo[c].adomain),
tmntag.vadtargets&&tmntag.vadtargets[c]&&(b=m(tmntag.vadtargets[c],["_cp","_pl","_pdid","_wb","_puids"],b)),tmntag.pubtargets&&(b=m(tmntag.pubtargets,["_ex","_rid"],b));c=b.bidderid||"3003";var d=b._pdid||"",f=b._puids||"",g=b.adomain||"",l=b._wb||"",t=b._cp||"",h=b._pl||"";window.tmntag_triggerEvent(a,{id:b._rid,pdid:d,puids:f,bid:l,cp:t,pl:h,z:"540x304",bdrid:c,ad:encodeURIComponent(g),e:b._ex,l:encodeURIComponent(window.tmntag_topLocation())})};h._videoView=function(a,b){q("VV",0,b),console.log("-RAMP VIDEO- Video View",
a)},h._videoServed=function(a,b){q("VS",0,b),console.log("-RAMP VIDEO- Video Served",a)},window.tmntag_videoBeforePlayListItem=function(a,d,c){if(console.log("-RAMP Video- tmntag_videoBeforePlayListItem"),void 0!==h.disableAds&&h.disableAds)console.log("-RAMP Video- Video Ads Disabled");else{var f=d.createInstream().init();(new b(function(b){tmntag.vadtargets=[],tmntag.markupsInfo=tmntag.markupsInfo||{},tmntag.markupsInfo[a]=[],void 0===h.status[a].fetch_count&&(h.status[a].fetch_count=0);var d=window.tmntag_getAdunitFromCache(a);
if(void 0===d||!d){d={div:c,sizes:[540,304]};void 0!==h.status[a].player_settings&&(d.targeting={apv:h.status[a].player_settings.autostart?1:0}),tmntag.adunit(d)}tmntag.videoRefresh(c,function(){b()})},3E3)).then(function(){f.destroy();var a=h.adTag(c,d.id);a?d.playAd(a):d.play()})}},h.setup=function(a,b,c){a&&a.div&&a.account&&(tmntag.account(a.account),tmntag.adunit({div:a.div,sizes:[540,304]}),h.start(a.div,b,c,a.div,!0))},h.start=function(a,b,c,d,f){void 0!==b.advertising&&b||(b.advertising={client:"googima"}),
tmntag.instartlogicEnabled()&&(b.advertising.client="vast"),b.advertising.autoplayadsmuted=!0,b.advertising.vpaidcontrols=!0,b.advertising.creativeTimeout=2E4,b.advertising.requestTimeout=2E4,b.advertising.loadVideoTimeout=2E4,b.advertising.adsRequestTimeout=2E4,b.advertising.maxRedirects=6,void 0!==d&&d||(d=a),f&&c.setup(b),h.status[a]={},h.status[a].errors=[],h.status[a].impressions=[],h.status[a].player_settings=b,(h.status[a].player=c).on("adError",function(f){"true"===tmntag._config.video_pause_on_error?
(h.logError(f),h.status[a].errors.push(f),b.autostart=!1,c.setup(b),c.on("playlistItem",function(){c.once("beforePlay",function(){h._videoView("event",d),window.tmntag_videoBeforePlayListItem(a,c,d)})}),c.on("adImpression",function(b){h._videoServed(b,d),h.status[a].impressions.push(b)})):(h.logError(f),h.status[a].errors.push(f))}),c.on("adImpression",function(b){h._videoServed(b,d),h.status[a].impressions.push(b)}),c.on("playlistItem",function(){c.once("beforePlay",function(){h._videoView(event,
d),window.tmntag_videoBeforePlayListItem(a,c,d)})}),"googima"===b.advertising.client&&r.init(c,a)},h.autostarted=function(a,b){h.status[a]&&h.status[a].player_settings&&(h.status[a].player_settings.autostart=b)},h.adTag=function(a,b){var c;return c=tmntag.instartlogicEnabled()?function(){var a=tmntag.vadtargets,b=0,c=0;if(void 0!==a)for(var d in a)for(var f=a[d],g=0;void 0!==f&&g<f.length;g++){if("_vst"===f[g][0]){var h=f[g][1];if(1<(h=h.split("/")).length)b=h[h.length-2]+"/"+h[h.length-1]}"_vrg"===
f[g][0]&&(c=f[g][1])}a="s3.amazonaws.com/purch-us-standard-adserver-prod";"or"===c?a="s3-us-west-2.amazonaws.com/purch-us-west-2-adserver-prod":"eu"===c&&(a="s3-eu-west-1.amazonaws.com/purch-eu-west-1-adserver-prod");c=Math.floor(11E3*Math.random());d="";return b&&(d="https://"+a+"/vast/"+b+"?cb="+c),d}():function(a,b){var c,d="",f=window.tmntag_getAdunitFromCache(a);if(f&&f.account)d=f.account;else{var g=window.tmntag_getAdUnit(a);g&&g.s?d=g.s:void 0!==tmntag.s&&tmntag.s&&(d=tmntag.s)}c=tmntag.l&&
1==tmntag.su?tmntag.l.replace("%",""):encodeURIComponent(window.tmntag_topLocation().replace("%",""));var g=tmntag.vadtargets,h=tmntag.pubtargets;a=tmntag.adtargets[a];var d=["sz="+(tmntag.isMobile()?"480x270":"640x480"),"iu="+d,"ciu_szs=728x90,300x250","impl=s","gdfp_req=1","env=vp","output=xml_vast3","unviewed_position_start=1","url="+c,"correlator=__timestamp__"],n=["plID="+b,"ttID=__item-mediaid__","vdbl=yes","vvid_title=__item-title__","pos=preroll","max_ad_duration=30000"];f.targeting&&Object.keys(f.targeting).forEach(function(a){n.push(a+
("="+f.targeting[a]))});b=!1;if(void 0!==h)for(var m in h)n.push(h[m][0]+"="+h[m][1]);if(void 0!==a)for(var l in a)n.push(a[l][0]+"="+a[l][1]);if(void 0!==g)for(var q in g){m=g[q];for(l=0;void 0!==m&&l<m.length;l++){if("_vst"===m[l][0]){b=m[l][1];if(1<(b=b.split("/")).length){b=b[b.length-2]+"/"+b[b.length-1];n.push("_vst="+b)}}else n.push(m[l][0]+"="+m[l][1]);b=!0}if(b)break}return"https://pubads.g.doubleclick.net/gampad/ads?"+d.join("&")+"&cust_params="+encodeURIComponent(n.join("&"))}(a,b),console.log("-RAMP VIDEO- Video Tag: "+
c),c};g.a=h},function(d,g,a){var b=a(4),f=a(5),u=a(9);g.a=function(a){if(Object(u.d)())Object(u.a)();else{var d=Object(b.a)("buzzarena.com|clubic.com|dailygeekshow.com|driverscloud.com|frandroid.com|frawin.com|futura-sciences.com|gamergen.com|generation-nt.com|hitek.fr|iaddict.com|iphoneaddict.fr|kulturegeek.fr|legeekcestchic.eu|monwindows.com|nexxdrive.fr|numerama.com|phonandroid.com|tablette-tactile.net|tomsguide.fr|tomshardware.co.uk|tomshardware.fr"),g=Object(b.a)("guitarworld.com|loudersound.com|anandtech.com|coinranking.com|dailydot.com|dignifyed.com|gamepressure.com|idownloadblog.com|laptopmag.com|livescience.com|newsarama.com|sciencealert.com|shopsavvy.com|space.com|tomsguide.com|tomshardware.com|tomsitpro.com|toptenreviews.com|xda-developers.com|creativebloq.com|realite-virtuelle.com|objetconnecte.net|howtogeek.com|androidcentral.com|crackberry.com|imore.com|modmy.com|windowscentral.com|technobuffalo.com|computing.net");(Object(f.a)(d)||a.gdprUser&&Object(f.a)(g))&&(a.__cmp=a.__cmp||function(){(window.attachEvent||window.addEventListener)("message",function(a){window.__cmp.receiveMessage(a)},!1),function c(){if(!window.frames.__cmpLocator)if(document.body){var a=
document.createElement("iframe");a.style.display="none",a.name="__cmpLocator",document.body.appendChild(a)}else setTimeout(c,5)}();var a=[],b=function(b,d,f){"ping"===b?f&&f({gdprAppliesGlobally:Boolean(window.__cmp&&window.__cmp.config&&window.__cmp.config.storeConsentGlobally),cmpLoaded:!1}):a.push({command:b,parameter:d,callback:f})};return b.commandQueue=a,b.receiveMessage=function(a){var b="string"==typeof a.data,c={};try{c=b?JSON.parse(a.data):a.data}catch(D){}if(c.__cmpCall){var d=c.__cmpCall;
window.__cmp(d.command,d.parameter,function(c,f){c={__cmpReturn:{returnValue:c,success:f,callId:d.callId}};a.source.postMessage(b?JSON.stringify(c):c,"*")})}},b}())}}},function(d,g,a){function b(){if(!G){G=!0;for(var a=0;a<L.length;a++)L[a].fn.call(window,L[a].ctx);L=[]}}function f(){"complete"===document.readyState&&b()}a.r(g);d=a(8);var u=a.n(d),r=a(19),m=a(3);d=a(24);g=a(15);var h=a(10),q=a(5),t=a(4),l=a(26),c=a(21),n=a(0),K=a(7),y=a(11),D=a(33);a.n(D);var D=a(27),z=a(9),M=a(22);window.TMNAPI_VERSION=
"tmnhead-5.25.0",window.TMNTAG_VERSION="1.4",window.TMNTAGVIDEOREFRESH_VERSION="1.0vr",window.PREBID_TIMEOUT=200,window.googletag=window.googletag||{},window.googletag.cmd=window.googletag.cmd||[];var F=function(a){window.tmntag.timing&&window.tmntag.timing.startTag&&window.tmntag.timing.loadTag&&(window.tmntag.timing.adunits[a]=window.tmntag.timing.adunits[a]||[],window.tmntag.timing.adunits[a].push({adLoadTime:(new Date).getTime()-window.tmntag.timing.startTag,tagLoadTime:window.tmntag.timing.startTag-
window.tmntag.timing.loadTag}))};window.tmntag_getAdUnitTiming=function(a){var b=window.tmntag.timing;return b&&b.adunits&&b.adunits[a]?window.tmntag.timing.adunits[a][window.tmntag.timing.adunits[a].length-1]:{adLoadTime:0,tagLoadTime:0}};a=function(){return"xxxxxxxxxxxx4xxxyxxxxxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"===a?b:3&b|8).toString(16)})};window.defuuid=a(),window.tmntag=window.tmntag||{},window.tmntag.cookies=h.a,window.tmntag._config=window.tmntag._config||
{},window.tmntag.config=window.tmntag.config||{},window.tmntag.config.get=function(a,b){return window.tmntag._config[a]||b},Object(D.a)(window);var x=function(a,b){var p=document.createElement("script");p.async=Boolean(b),p.type="text/javascript",p.src=a;(a=document.getElementsByTagName("script")[0]||document.getElementsByTagName("body")[0])&&a.parentNode.insertBefore(p,a)},C,L,G,N,v;x("//www.googletagservices.com/tag/js/gpt.js",!0),C=window,L=[],G=!1,N=!1,C.tmntag_ready=function(a,k){G?setTimeout(function(){a(k)},
1):(L.push({fn:a,ctx:k}),"complete"===document.readyState||!document.attachEvent&&"interactive"===document.readyState?setTimeout(b,1):N||(document.addEventListener?(document.addEventListener("DOMContentLoaded",b,!1),window.addEventListener("load",b,!1)):(document.attachEvent("onreadystatechange",f),window.attachEvent("onload",b)),N=!0))},v=function(){for(var a=0;window.tmntagCache&&a<window.tmntagCache.length;a++)if(window.tmntagCache[a]&&window.tmntagCache[a].isMouseOver){var b=Math.floor(11E3*Math.random()),
e="https:"===document.location.protocol?"https://":"http://",c=void 0!==window.context&&window.context||!top.window.experiments?"":top.window.experiments,b="".concat(e,"ads2.servebom.com/event.js?t=CC&id=").concat(top.window.requestid?top.window.requestid:0,"&bid=&cp=0&bdrid=&crid=&e=").concat(c,"&ad=&r=").concat(b);x(b,!1)}},window.addEventListener&&(window.addEventListener("blur",v),window.addEventListener("focusout",v),window.addEventListener("focus",function(){window.addEventListener("blur",v)}));
var E=function(a){for(var b=0;b<window.tmntag.a.length;b++)if(window.tmntag.a[b].d===a)return window.tmntag.a[b];return!1};window.tmntag_getAdUnit=E;var O=function(){var a=new Date,b=function(a){return(a<=9?"0":"")+a},e=a.getDate(),c=a.getFullYear(),d=a.getMonth()+1,f=a.getHours(),g=a.getMinutes(),a=a.getSeconds();return"".concat(c,"-").concat(b(d),"-").concat(b(e)," ").concat(b(f),":").concat(b(g),":").concat(b(a))},B=function(a){return a.constructor===Array};window.tmntag_isArray=B,window.tmntag_getAdunitFromCache=
function(a){return window.tmntagCache.find(function(b){return b.div&&b.div===a})||null},window.tmntag_registerMouseOver=function(a){var b=window.tmntag_getAdunitFromCache(a);a=document.querySelector("#".concat(a," iframe"));b&&a&&(a.addEventListener("mouseover",function(){b.isMouseOver=!0}),a.addEventListener("mouseout",function(){b.isMouseOver=!1}))};var I=function(a){var b=Object(n.g)(a,"incontent_css_selector");b&&window.MultipleIncontent(a,b,{position:Object(n.g)(a,"incontent_position"),repetitionMob:Object(n.g)(a,
"incontent_limit_mobile"),repetitionDesk:Object(n.g)(a,"incontent_limit_desktop"),elementsFormula:Object(n.g)(a,"incontent_elements_formula"),progressive:Object(n.g)(a,"incontent_progressive")})},J=function(a){return!!window.tmntag.instartlogicEnabled()||window.tmntag&&window.tmntag.markupsInfo&&window.tmntag.markupsInfo[a]&&window.tmntag.markupsInfo[a].inline},H=function(a){var b=!1,p=window.tmntag_getAdunitFromCache(a);if(!p||!J(a))return b;I(a);var c=document.getElementById(a);if(!c)return b;var d=
window.tmntag.markupsInfo[a];if(d&&p){p="".concat(a,"_tmntag_inline_");(b=document.getElementById(p))&&c.removeChild(b);b=document.createElement("div");b.id=p,b.style.border="0pt none",b.style.display="inline-block",b.style.width="".concat(d.width||0,"px"),b.style.height="".concat(d.height||0,"px"),b.style.margin="0px",b.style.padding="0px";var f=d.iframe,p=window.tmntag.markups[a];if(p=p.replace(/'\r\n|\r|\n/gm,""),f||window.tmntag.instartlogicEnabled()){f=document.createElement("iframe");f.frameBorder=
0,f.scrolling="no",f.marginwidth=0,f.marginheight=0,f.style.width="".concat(d.width||0,"px"),f.style.height="".concat(d.height||0,"px"),f.style.border="0pt none",f.style.margin="0px 0 0",f.width=d.width||0,f.height=d.height||0,b.appendChild(f),c.appendChild(b);c='<!DOCTYPE html><body marginheight="0" marginwidth="0">'.concat(p,"</body></html>");f.contentDocument.open(),f.contentDocument.write(c),f.contentDocument.close()}else b.innerHTML=p,c.appendChild(b);window.tmntag.onInlineAdunitRendered({divid:a,
size:{width:d.width||0,height:d.height||0}}),b=!0}return b};window.tmntag_inlineMarkup=H,window.tmntag_defineSlot=function(a,b,e){var p,k=E(a),c=window.tmntag_getAdunitFromCache(a);try{if(J(a))return H(a),null}catch(Z){return console&&console.error&&console.error(Z),null}if(e)p=window.tmntag.slots[a];else{if(k.z)p=window.googletag.defineSlot(k.s,k.z,k.d).addService(window.googletag.pubads()),window.tmntag.ced&&p.setCollapseEmptyDiv(!0,!0);else{p=document.getElementById(k.d);p&&(p.style.height="0px"),
p=window.googletag.defineOutOfPageSlot(k.s,k.d).addService(window.googletag.pubads())}k.c&&p.addService(window.googletag.companionAds().setRefreshUnfilledSlots(k.c)),c&&void 0!==c.sizeMapping&&p.defineSizeMapping(c.sizeMapping),window.tmntag.slots[a]=p}if(b=b||k&&k.g)for(var d in b)b.hasOwnProperty(d)&&p.setTargeting(d,b[d]);if(void 0!==window.tmntag.adtargets){a=window.tmntag.adtargets[k.d];if(void 0!==a&&window.tmntag.localAdtargets&&void 0!==window.tmntag.localAdtargets[k.d])for(b=0;b<window.tmntag.localAdtargets[k.d].length;b++)a.push(window.tmntag.localAdtargets[k.d][b]);
e&&p&&p.clearTargeting();for(e=0;p&&void 0!==a&&e<a.length;e++)void 0!==window.tmntag_disablertb&&window.tmntag_disablertb&&"_br"===a[e][0]||p.setTargeting(a[e][0],a[e][1])}return p},window.tmntag_defineAdUnit=function(a){var b=window.tmntag_getAdunitFromCache(a);void 0===b.adunitRule?1===b.refresh?(window.tmntag_defineSlot(a,{},!0),b.refresh=0):1!==window.tmntag.f&&(window.tmntag_defineSlot(a),I(a)):(1===b.refresh&&(window.tmntag_defineSlot(a,{},!0),b.refresh=0),window.tmntag.enableSingleRequest())};
var w=function(){window.tmntag_gptloaded=!0},P=function(){try{var a=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,b=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight;return"".concat(a,"x").concat(b)}catch(e){console.error(e)}return null};window.tmntag_topLocation=function(){try{return window.context&&window.context.location&&window.context.location.href?window.context.location.href:window.top.document.location.href}catch(p){return window.document.referrer}};
var R=function(){try{return window.context&&window.context.referrer?window.context.referrer:window.top.document.referrer}catch(p){return""}};C=function(){try{if(navigator.mimeTypes&&0<navigator.mimeTypes.length){var a=navigator.mimeTypes["application/x-shockwave-flash"];if(a&&a.enabledPlugin)return 1}else if("undefined"!=typeof ActiveXObject)try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash.1"),1}catch(k){}}catch(k){console&&console.error&&console.error(k)}return 0};window.tmntag_gptloaded=
!1,window.tmntag_callbacks=new function(){this.callback=[],this.callback_executed=[],this.pushCallback=function(a,b){void 0!==b?this.callback.push({callback:a,params:b}):this.callback.push({callback:a})},this.executeCallbacks=function(){var a=this.callback.length;if(0<a)for(var b=0;b<a;){var e=this.callback[0];void 0!==e.params?e.callback.apply(null,e.params):e.callback(),this.callback.splice(0,1),this.callback_executed.push(e),b++}}},window.tmntag_initialLoadDisabled=!1,window.tmntag_initialLoadDisabledMode=
!1,window.tmntagCache=[],window.tmntag.cmd=window.tmntag.cmd||[],window.tmntagDisplayed={},window.tmntag.timing={},window.tmntag.timing.adunits={},window.tmntag.timing.start=(new Date).getTime(),window.tmntag.sr=!0,window.tmntag.ced=!0,window.tmntag.a=[],window.tmntag.slots={},window.tmntag.l=encodeURIComponent(window.tmntag_topLocation().replace("%","")),window.tmntag.tt=encodeURIComponent(document.title?document.title.replace("|",""):""),window.tmntag.t=O(),window.tmntag.tz=Math.round((new Date).getTimezoneOffset()),
window.tmntag.r=P(),window.tmntag.su=0,window.tmntag.fs=C(),window.tmntag.disabledAdunits=[],window.tmntag.disableDFPRefresh=!1,window.tmntag.onAdunitRenderedCallbackFunction=function(){},window.tmntag.video=l.a,window.tmntag.safeFunctionCall=function(a,b){return"function"==typeof window[a]?window[a].apply():b||""},window.tmntag.instartlogicEnabled=function(){return window.I11C&&1===window.I11C.Morph},window.tmntag.placementCustomID=function(a){window.tmntag.pc=a},window.tmntag.getAdParameters=n.g,
window.tmntag.placement=function(a){window.tmntag.p=a},window.tmntag.account=function(a){a=a&&a.replace(/\t|\s+/gm,""),window.tmntag.s=a};var A=function(a,b,e){for(var k=a.length-1;0<=k;k--){var p=a[k];p[b]&&p[b]===e&&a.splice(k,1)}};window.tmntag.adunit=function(a){if(window.tmntag.disabledAdunits.find(function(b){return b===a.div}))return null;var b=window.tmntag_getAdunitFromCache(a.div);if(b){for(var e in a)b[e]=a[e];a=b}b={};return a.account?b.s=a.account:window.tmntag.s&&(b.s=window.tmntag.s),
a.sizes&&(b.z=a.sizes),a.div&&(b.d=a.div),a.targeting?(b.g=a.targeting,a.atf=a.targeting._a):b.g={},a.atf&&("1"===a.atf?b.a="true":"0"===a.atf&&(b.a="false")),a.companion&&(b.c=a.companion),a.div&&(A(window.tmntag.a,"d",a.div),A(window.tmntagCache,"div",a.div)),a.sizeMapping&&(b.sm=a.sizeMapping),window.tmntag.a.push(b),window.tmntagCache.push(a),b},window.tmntag.adunitTarget=function(a,b,e){if("object"===u()(a))a.g[b]=e;else if("string"==typeof a){var k=window.tmntag.localAdtargets=window.tmntag.localAdtargets||
[];k[a]=k[a]||[],k[a].push([b,e])}},window.tmntag.target=function(a){try{if("object"!==u()(a)||a instanceof Array)return;for(var b in window.tmntag.g||(window.tmntag.g=a),a)if(a.hasOwnProperty(b)){var e=a[b];if(e&&B(e)){for(var p=0;p<e.length;p++)e[p]=String(e[p]),e[p]=e[p].replace(/'|;|quot;|39;|&amp;|&|#|\r\n|\r|\n|\t|\f|%0A|"|%22|%5C|%23|%26|%26|%09/gm,""),e[p]=e[p].replace(/%/gm,"");window.tmntag.g[b.replace(/'|&|#/g,"")]=e}else e&&(b=b.replace(/'|&|#/g,""),e="".concat(e),window.tmntag.g[b]=e.replace(/'|;|quot;|39;|&amp;|&|#|\r\n|\r|\n|\t|\f|%0A|"|%22|%5C|%23|%26|%26|%09/gm,
""),window.tmntag.g[b]=window.tmntag.g[b].replace(/%/gm,""))}}catch(aa){console&&console.error&&console.error(aa)}},window.tmntag.location=function(a){window.tmntag.l=encodeURIComponent(a),window.tmntag.su=1};var U=function(a){var b=Object(n.g)(a);if(b)if(b=b.adunit_style){a=document.getElementById(a);for(var b=b.trim().split(";"),e=0;e<b.length;e++)if(""!==b[e]){var p=b[e].split(":"),c=null;p[1]&&(0<=p[1].indexOf("!important")&&(p[1]=p[1].replace("!important",""),c="important"),a.style.setProperty(p[0].trim(),
p[1].trim(),c))}}};window.tmntag.adTag=function(a,b){try{if(window.tmntag.disabledAdunits.find(function(b){return b===a}))return;var e=window.tmntag_getAdunitFromCache(a);if(!e||null===e)return void(void 0!==b&&!b||document.getElementById(a)?void 0===b?window.tmntag_callbacks.pushCallback(window.tmntag.adTag,[a]):window.tmntag_callbacks.pushCallback(window.tmntag.adTag,[a,b]):(window.tmntag_callbacks.pushCallback(window.tmntag.adTag,[a,!1]),void 0===b&&document.write('<div id="'.concat(a,'"></div>'))));
var k=void 0!==e.adunitRule&&"function"==typeof e.adunitRule&&!0===e.adunitRule(a);if(void 0===e.adunitRule||k){if(void 0!==b&&!b||document.getElementById(a)||document.write('<div id="'.concat(a,'"></div>')),!e.sizes){var p=document.getElementById(a);p&&(p.style.height="0px")}U(a),k?window.googletag.cmd.push(function(){document.getElementById(a)&&window.tmntag?(window.tmntag.slots&&!window.tmntag.slots[a]&&(1===e.refresh?(window.tmntag_defineSlot(a,{},!0),e.refresh=0):window.tmntag_defineSlot(a)),
window.googletag.display(a)):window.tmntagDisplayed[a]=1}):window.googletag.cmd.push(function(){document.getElementById(a)&&window.tmntag&&window.tmntag.slots&&window.tmntag.slots[a]?window.googletag.display(a):window.tmntagDisplayed[a]=1})}}catch(ba){console&&console.error&&console.error(ba)}},window.tmntag.loadScript=function(a,b,e){var k=null!=e,p="function"==typeof b,c=document.createElement("script");c.async=!0,c.src=a;var d;a=document.getElementsByTagName("script")[0];k?d=setTimeout(function(){clearTimeout(d),
p&&b()},e):p&&(c.onload=b),a.parentNode.insertBefore(c,a)};var S=function(a,b,e,c){a=(a=a||[])instanceof Array?a:[a];var k=b=b.filter(function(a){return a.d}),p=window.tmntag.markupsInfo;return!c&&e&&window.tmntag.disableDFPRefresh&&(k=b.filter(function(b){return-1!==a.indexOf(b.d)}).filter(function(a){return p[a.d]&&p[a.d].rtbSold})),0===a.length?k:k.filter(function(b){return-1<a.indexOf(b.d)})};window.tmntag_filterAdUnitsByIds=S;window.tmntag.addCookies=function(){var a={},b=window.tmntag.cookies.get("up_28");
void 0!==b&&(a.up_28=b);b=window.tmntag.cookies.get("D_TOKEN");return void 0!==b&&(a.D_TOKEN=b),a},window.tmntag.getParams=function(){return""===window.location.search?{}:window.location.search.substr(1).split("&").reduce(function(a,b){var e=b.indexOf("=");return a[b.substr(0,e)]=b.substr(e+1),a},{})},window.tmntag.setPersonalizedAdsMode=m.d,window.tmntag.getPersonalizedAdsMode=m.c,window.tmntag_formateMacromapList=t.a,function(){if(!Object(z.d)()){var a=Object(t.a)("fredzone.org|homecinema-fr.com|lemondenumerique.com|tomshw.it"),
b=Object(t.a)("buzzarena.com|clubic.com|dailygeekshow.com|driverscloud.com|frandroid.com|frawin.com|futura-sciences.com|gamergen.com|generation-nt.com|hitek.fr|iaddict.com|iphoneaddict.fr|kulturegeek.fr|legeekcestchic.eu|monwindows.com|nexxdrive.fr|numerama.com|phonandroid.com|tablette-tactile.net|tomsguide.fr|tomshardware.co.uk|tomshardware.fr"),e=Object(t.a)("guitarworld.com|loudersound.com|anandtech.com|coinranking.com|dailydot.com|dignifyed.com|gamepressure.com|idownloadblog.com|laptopmag.com|livescience.com|newsarama.com|sciencealert.com|shopsavvy.com|space.com|tomsguide.com|tomshardware.com|tomsitpro.com|toptenreviews.com|xda-developers.com|creativebloq.com|realite-virtuelle.com|objetconnecte.net|howtogeek.com|androidcentral.com|crackberry.com|imore.com|modmy.com|windowscentral.com|technobuffalo.com|computing.net");Object(m.d)("allowed"),Object(q.a)(a)?Object(m.d)("blocked"):Object(q.a)(b)?Object(m.d)("managed"):window.gdprUser&&(Object(q.a)(e)?Object(m.d)("managed"):Object(m.d)("blocked"))}}(),window.tmntag_serializeState=function(a,b,e,c,d){e={};a=(e.f=a?1:"",e.p=a?"":window.tmntag.p,e.fmt=window.tmntag.fmt||"WEB",e.s=window.tmntag.s,e.g=window.tmntag.g,e.l=window.tmntag.l,
e.tt=window.tmntag.tt,e.tt=e.tt.replace(/'|;|quot;|39;|&amp;|&|#|\r\n|\r|\n|\t|\f|%0A|"|%22|%5C|%23|%26|%26|%09/gm,""),e.fs=window.tmntag.fs,e.a=S(b,window.tmntag.a||[],a,c),e.t=O(),e.ck=window.tmntag.addCookies(),e.tz=Math.round((new Date).getTimezoneOffset()),e.r=P());{a:{b=window.tmntag.cookies.get("DigiTrust.v1.identity");if(void 0===b){b=null;break a}b=JSON.parse(atob(decodeURIComponent(b)));b=encodeURIComponent(btoa(JSON.stringify({id:b.id,keyv:b.keyv})))}}a,e.dgt=b,e.rf=encodeURIComponent(R().replace("%",
"")),e.pam=window.tmntag.getPersonalizedAdsMode(),e.gdpr_consent=d;d=window.tmntag.getParams();a=decodeURIComponent(d.key);if(d.key&&-1!==atob(a).indexOf(",")){d=atob(a).split(",");e.g=e.g||{},e.g.kw=e.g.kw||[],"string"==typeof e.g.kw&&(e.g.kw=[e.g.kw]),e.g.kw=e.g.kw.concat(d)}return JSON.stringify(e).replace(/'|&|#/g,"")};var V=function(a,b){var e=[];if(void 0!==a){if(a instanceof Array)for(var k in a){var c=window.tmntag.slots[a[k]];c&&e.push(c)}else(k=window.tmntag.slots[a])&&e.push(k);if(0<e.length){for(var p in e)if(e.hasOwnProperty(p)&&
b)for(var d in e[p].clearTargeting(),b)b.hasOwnProperty(d)&&e[p].setTargeting(d,b[d]);window.googletag.pubads().refresh(e)}console&&console.info&&console.info("-RAMP- Regular refresh ".concat(a))}else window.googletag.pubads().refresh()};window.tmntag.refresh=function(a,b,e){a&&(a=B(a)?a:[a]).forEach(function(a){var b=window.tmntag_getAdunitFromCache(a),k=window.tmntag.adtargets[a]&&window.tmntag.adtargets[a].find(function(a){return"_trn"===a[0]});if(void 0===e||b.targeting._trn){if(void 0===e&&b&&
b.targeting&&b.targeting._trn&&window.tmntag.adtargets[a]){k=window.tmntag.adtargets[a].indexOf(k);window.tmntag.adtargets[a].splice(k,1),delete b.targeting._trn}}else window.tmntag.adtargets[a]=window.tmntag.adtargets[a]||[],window.tmntag.adtargets[a].push(["_trn",e]),b.targeting._trn=e});a=S(a,window.tmntag.a||[],!0,!1);for(var k=[],c=0;c<a.length;c++)k.push(a[c].d);k.forEach(function(a){window.tmntag.markupsInfo&&window.tmntag.markupsInfo[a]&&(window.tmntag.markupsInfo[a]={})}),window.tmntag.start(!0,
k,function(){V(k,b),window.tmntag.events.dispatchEvent("refresh",{divIds:k,trn:e})})},window.tmntag.refreshPixels=function(){if(void 0!==window.tmntag.tmn_pixels)for(var a=0;a<window.tmntag.tmn_pixels.length;a++){var b=window.tmntag.tmn_pixels[a];b.isRefreshable()&&b.execute()}},window.tmntag_redirect=function(a,b,e){if(!a)return!1;var k={cp:"__CP__",bdrid:"__BDRID__",crid:"__CRID__",ad:"__AD__",pd:"__PRODUCT_ID__",tid:"__TID__",pvid:"__PVID__"};a="object"===u()(b)?a.href:b;e="object"===u()(b)?b:
e;b=Math.floor(11E3*Math.random());var c="https:"===document.location.protocol?"https://":"http://";e="".concat(c,"ramp.purch.com/event.js?t=CL&id=").concat(top.window.requestid?top.window.requestid:0,"&r=").concat(b).concat(function(a){var b="";if(a&&k)for(var e in k)k.hasOwnProperty(e)&&a.hasOwnProperty(k[e])&&(b+="pd"===e?"&".concat(e,"=|").concat(a[k[e]],"|"):"&".concat(e,"=").concat(a[k[e]]));return b}(e));return x(e,!1),window.open(a,"_blank").focus(),!1},window.tmntag_triggerEvent=function(a,
b){var e="";if(b)for(var k in b){""!==e&&(e+="&");var c="".concat(b[k]);-1===c.indexOf("$")&&(e+="".concat(k,"=").concat(c))}k=Math.floor(11E3*Math.random());c=window.tmntag.instartlogicEnabled()?"1":"";e="t=".concat(a,"&r=").concat(k,"&abr=").concat(c,"&").concat(e),"CP"===a&&(b&&b.ts&&-1===b.ts.indexOf("$")&&(e="".concat(e,"&tm_alt=").concat(Date.now()-b.ts)),window.tmntag.timing&&window.tmntag.timing.startTag&&window.tmntag.timing.loadTag&&(e="".concat(e,"&tm_tlt=").concat(window.tmntag.timing.startTag-
window.tmntag.timing.loadTag)));a=document.createElement("script");a.src="//ads2.servebom.com/event.js?".concat(e);e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)},window.tmntag_disableAdunit=function(a){window.tmntag.disabledAdunits.push(a)},window.tmntag_enableAdunit=function(a){window.tmntag.disabledAdunits.splice(window.tmntag.disabledAdunits.indexOf(a),1)},window.tmntag.adunitNew=function(a,b){if(!window.tmntag.disabledAdunits.find(function(b){return b===a.div})){window.tmntag.adunit(a);
var e=a.div;window.tmntag_defineSlot(e),window.googletag.display(e),b&&window.tmntag.refresh(e)}},window.tmntag.multipleAdunitClone=r.b,window.tmntag.adunitClone=r.a,window.tmntag.disableSingleRequest=function(){window.tmntag.sr=!1},window.tmntag.disableCollapseEmptyDivs=function(){window.tmntag.ced=!1},window.tmntag.enableSingleRequest=function(){window.tmntag.sr=!0},window.tmntag.disableInitialLoad=function(){window.tmntag_initialLoadDisabled=!0,window.tmntag_initialLoadDisabledMode=!0},window.tmntag.onInlineAdunitRendered=
function(a){var b=a.divid,e=window.tmntag_getAdunitFromCache(b),d={};d.div=b,d.adunit=e,a.size?d.size={width:a.size[0],height:a.size[1]}:d.size={width:0,height:0},d.isEmpty=!1,d.dfpCreativeId="",d.dfpLineItemId="",d.dfpCampaignId="",e.dfpCreativeId="",e.dfpLineItemId="",e.dfpCampaignId="",d._orig=a,window.tmntag_registerMouseOver(b),void 0!==window.tmntag_adlabel&&window.tmntag_adlabel&&window.tmntag_adlabel.render(b,d),window.tmntag.onAdunitRenderedCallbackFunction(d),e&&e.onAdunitRendered&&"function"==
typeof e.onAdunitRendered&&e.onAdunitRendered(a),Object(M.a)(b),Object(c.a)(b),F(b)},window.tmntag.onAdunitRenderedPrivate=function(a){var b=a.slot.getSlotId().getDomId(),e=window.tmntag_getAdunitFromCache(b),d={};if(d.div=b,d.adunit=e,a.size&&1<a.size[0]&&1<a.size[1]?d.size={width:a.size[0],height:a.size[1]}:window.tmntag.markupsInfo&&window.tmntag.markupsInfo[b]?d.size={width:window.tmntag.markupsInfo[b].width,height:window.tmntag.markupsInfo[b].height}:d.size={width:0,height:0},d.isEmpty=a.isEmpty,
d.dfpCreativeId=a.creativeId||a.sourceAgnosticCreativeId,d.dfpLineItemId=a.lineItemId||a.sourceAgnosticLineItemId,d.dfpCampaignId=a.campaignId,e&&(e.dfpCreativeId=a.creativeId||a.sourceAgnosticCreativeId,e.dfpLineItemId=a.lineItemId||a.sourceAgnosticLineItemId,e.dfpCampaignId=a.campaignId),d._orig=a,window.tmntag_registerMouseOver(b),void 0!==window.tmntag_adlabel&&window.tmntag_adlabel&&window.tmntag_adlabel.render(b,d),F(b),window.tmntag.adunitServedEvent&&1<d.size.width&&1<d.size.height){var f=
{};window.tmntag.markupsInfo&&window.tmntag.markupsInfo[b]&&(f.bidderid=window.tmntag.markupsInfo[b].bidderid,f.adomain=window.tmntag.markupsInfo[b].adomain),window.tmntag.adtargets&&window.tmntag.adtargets[b]&&(f=Object(n.b)(window.tmntag.adtargets[b],["_cp","_pl","_pdid","_wb"],f)),window.tmntag.pubtargets&&(f=Object(n.b)(window.tmntag.pubtargets,["_ex","_rid"],f));var p=f._pdid||"",g=f.adomain||"",w=f._cp||"",H=f._pl||"",h=f.bidderid||"3003",m=window.tmntag_getAdUnitTiming(b);window.tmntag_triggerEvent("AS",
{id:f._rid,pdid:p,bid:f._wb,cp:w,pl:H,bdrid:h,ad:encodeURIComponent(g),e:f._ex,l:encodeURIComponent(window.tmntag_topLocation()),z:"".concat(d.size.width,"x").concat(d.size.height),crid:encodeURIComponent(b),tm_alt:m.adLoadTime,tm_tlt:Math.max(0,m.tagLoadTime)})}try{window.tmntag.onAdunitRenderedCallbackFunction(d)}catch(ca){console.log(ca)}e&&e.onAdunitRendered&&"function"==typeof e.onAdunitRendered&&e.onAdunitRendered(a),Object(M.a)(b),Object(c.a)(b)},window.tmntag.onAdunitViewablePrivate=function(a){a=
a.slot.getSlotId().getDomId();(a=window.tmntag_getAdunitFromCache(a))&&(a.viewable=!0)},window.tmntag.onAdunitRendered=function(a){a="function"==typeof a?a:function(){},this.callbacks=this.callbacks||[],this.callbacks.push(a),window.tmntag.onAdunitRenderedCallbackFunction=function(){for(var a=arguments.length,b=new Array(a),c=0;c<a;c++)b[c]=arguments[c];this.callbacks.forEach(function(a){a.apply(void 0,b)})}.bind(this)},window.tmntag_xhrGet=function(a,b,e){var c=new XMLHttpRequest;c.withCredentials=
!0,e&&(c.timeout=e),c.open("GET",a,!0),c.onreadystatechange=function(){this.readyState===XMLHttpRequest.DONE&&b(this.responseText)},c.send(null)};var Q=function(){for(var a=0;a<document.scripts.length;a++){var b=document.scripts[a],e=b.src.indexOf("tmnhead.js");if(0<e)return b.src.substring(0,e)}return"http://ads.servebom.com/"};window.tmntag_executingStart=!1,window.tmntag.start=function(a,b,e,c,d,f,g,w){function k(a,b){eval("try { ".concat(a," } catch (e) { console.error(e); }"))}function p(a,b,
e){window.tmntag_xhrGet(a,function(a){k(a),b()},e)}function H(a,b){return"".concat(a,"tmntag.js?").concat(Object.keys(b).map(function(a){return"".concat(a,"=").concat(b[a])}).join("&"))}w=w||"";var h=function(a,b,e,c,k,g,w){if(g&&window.tmntag.location(g),!window.tmntag_executingStart||a){a||(window.tmntag.enableSingleRequest(),window.googletag.cmd.push(function(){window.googletag.pubads().addEventListener("slotRenderEnded",function(a){window.tmntag.onAdunitRenderedPrivate(a)}),window.googletag.pubads().addEventListener("impressionViewable",
function(a){window.tmntag.onAdunitViewablePrivate(a)})})),window.tmntag_executingStart=!0;var h=Math.floor(11E3*Math.random());g=Q();var m=[];if("undefined"!=typeof amznads&&null!==window.amznads&&"function"==typeof window.amznads.getTokens){var l=window.amznads.getTokens();if(null!==l&&0<l.length){l=l.join();l=l.replace("kindle_pur_3x6","a3x6p100"),m.push({br:6,bs:l})}}if("object"===("undefined"==typeof prebidSlots?"undefined":u()(prebidSlots))&&null!==window.prebidSlots)for(var n in window.prebidSlots)if(window.prebidSlots.hasOwnProperty(n)){var l=
window.prebidSlots[n],q=[],P;for(P in l){var r=l[P];"object"===u()(r)&&q.push("a".concat(r.width,"x").concat(r.height,"p").concat(r.cpm,":").concat(r.ad))}0<q.length&&m.push({br:n,bs:q.join()})}n={};n.v=d||window.TMNTAG_VERSION,n.r=h,n.o=window.tmntag_serializeState(a,b,f,k,w),a&&"v"!==f&&(window.tmntag.f=1);b=S(b,window.tmntag.a||[],a,k);if(a&&b)for(k=0;k<b.length;k++)(w=window.tmntag_getAdunitFromCache(b[k].d))&&(w.refresh=1);n.uuid=window.defuuid,"undefined"!=typeof Purch&&window.Purch.calypso&&
window.Purch.calypso.pvid&&(n.pvid=window.Purch.calypso.pvid),0<m.length&&(n.j=JSON.stringify(m)),n.at=f||"bnj",window.tmntag.instartlogicEnabled()&&(n.abr=1);var A=H(g,n);a?p(A,e,c):window.tmntag.cmd.push(function(){window.tmntag.loadScript(A)}),window.tmntag.timing.loadTag=(new Date).getTime()}};a&&(window.amznads=null),Object(z.d)()?Object(m.e)().then(Object(m.b)()).then(function(d){var k=d.gdprApplies;d=d.consentData;Object(m.d)(k?"managed":"allowed");var f=k?d:null;"undefined"!=typeof amznads&&
window.amznads&&window.amznads.asyncParams?setTimeout(function(){h(a,b,e,c,g,w,f)},window.PREBID_TIMEOUT):(window.PREBID_TIMEOUT=0,h(a,b,e,c,g,w,f))}):"undefined"!=typeof amznads&&window.amznads&&window.amznads.asyncParams?setTimeout(function(){h(a,b,e,c,g,w)},window.PREBID_TIMEOUT):(window.PREBID_TIMEOUT=0,h(a,b,e,c,g,w))},window.tmntag_passback=function(a,b){if(b){var e=b.split("|");1===e.length&&window.tmntag_render(a,b),4<=e.length&&(window.tmntag_render(a,e[0])||a.write('<script type="text/javascript">google_ad_client = "ca-pub-5787592483766760";\ngoogle_ad_slot = "'+
e[3]+'";\ngoogle_ad_width = '+e[1]+";\ngoogle_ad_height = "+e[2]+';\x3c/script><script type="text/javascript" src="//pagead2.googlesyndication.com/pagead/show_ads.js">\x3c/script>'))}},window.tmntag.videoRefresh=function(a,b){console.log("-RAMP VIDEO- Refresh");var e=function(){};"function"==typeof b&&(e=b),window.tmntag.start(!0,a,e,null,window.TMNTAGVIDEOREFRESH_VERSION,"v")},window.tmntag.processAdResponse=function(a){window.tmntag_initialLoadDisabled&&(window.tmntag_initialLoadDisabled=!1,window.googletag.cmd.push(function(){V(a)}))};
var da=function(a,b,e){var c;return function(){var d=this,k=arguments,f=e&&!c;clearTimeout(c),c=setTimeout(function(){c=null,e||a.apply(d,k)},b),f&&a.apply(d,k)}},ea=function(a){var b=!1;return void 0!==window.tmntag.adtargets&&void 0!==window.tmntag.adtargets[a]&&window.tmntag.adtargets[a].forEach(function(a){b=b||"_ll"===a[0]&&a[1]}),b},W=function(a,b,e){var c=window.tmntag.markupsInfo[b].width,d=window.tmntag.markupsInfo[b].height;if("function"==typeof confiantWrapWithCallback&&window.CONFIANT_WRAPPER_ID){var k=
window.tmntag.markupsInfo[b].biddername,f="purch_".concat(k);e={ad:e,bidder:f,size:"".concat(c,"x").concat(d),cpm:window.tmntag.adtargets[b]&&window.tmntag.adtargets[b].find(function(a){return"_cp"===a[0]})[1]};window.confiantWrapWithCallback(a,e,"clarium.global.ssl.fastly.net",window.CONFIANT_WRAPPER_ID,function(a,e,k,g,p,w){window.tmntag_triggerEvent("CB",{bdrid:window.tmntag.markupsInfo[b].bidderid||0,tid:"".concat(f,":").concat(c,"x").concat(d),crid:e,ad:a,cp:w.prebid.cpm,id:window.requestid})})||
(a.write(e.ad),a.close())}else a.write(e),a.close();(e=window.tmntag.slots[b])&&e.setTargeting("_bd","none");e=window.tmntag.markupsInfo[b];if(e&&(e.rtbSold=!0),a.defaultView&&a.defaultView.frameElement){e="".concat(c,"px");k="".concat(d,"px");a.defaultView.frameElement.width=e,a.defaultView.frameElement.height=k,top!==self&&self&&self.frameElement&&(self.frameElement.width=e,self.frameElement.height=k)}};window.tmntag_render=function(a,b){var e=!1;if(void 0!==window.tmntag.markups){var c=window.tmntag.markups[b];
if(null!=c)if(c=(c=c.replace("a3x6p100","kindle_pur_3x6")).replace(/'\r\n|\r|\n/gm,""),ea(b)){var d=da(function(){var e;{a:{var f=b,k=void 0;e=void 0;if(k=k||0,e=e||"visible",null===document.querySelector("#".concat(f))){e=null;break a}var g=document.querySelector("#".concat(f)).getBoundingClientRect(),w=Math.max(document.documentElement.clientHeight,window.innerHeight),f=g.bottom-k<0,k=0<=g.top-w+k;e="above"===e?f:"below"===e?k:!f&&!k}}e&&(document.removeEventListener("scroll",d),W(a,b,c))},50);
document.addEventListener("scroll",d),d()}else W(a,b,c),e=!0}return e},window.tmntag_ready(function(){if(window.tmntag)for(var a=0;a<window.tmntag.a.length;a++)H(window.tmntag.a[a].d)}),window.tmntag.multipleInContentSelectors=window.tmntag.multipleInContentSelectors||{},window.tmntag.multipleInContentParams=window.tmntag.multipleInContentParams||{},window.tmntag.multipleInContent=function(a,b){b=b||{};var e=window.tmntag.multipleInContentSelectors[a];!e&&b.selector&&(e=b.selector),b.clone=!0,Object.assign(b,
window.tmntag.multipleInContentParams&&window.tmntag.multipleInContentParams[a]||{}),e&&window.MultipleIncontent(a,e,b)};var fa=(X=function(a){window.tmntag.inView(".ramp-incontent-progressive").on("enter",function(b){b.classList.contains("ramp-incontent-progressive")&&window.tmntag.multipleInContent(a)})},T=!1,function(){var a;return T||(a=X.apply(void 0,arguments)),T=!0,a}),X,T;window.MultipleIncontent=function(a,b,e){function c(a,b,e){a.parentNode&&a.parentNode.removeChild(a),b.insertAdjacentHTML(e,
a.outerHTML),U(a.id)}(e=e||{}).position=e.position||"afterend";var d=e[window.tmntag.isMobile()?"repetitionMob":"repetitionDesk"];if(window.tmntag.multipleInContentSelectors[a]=b,window.tmntag.multipleInContentParams=window.tmntag.multipleInContentParams||{},window.tmntag.multipleInContentParams[a]=e,!a||!b)return!1;var f=[];b=function(a,b){var e=[];try{e=Array.prototype.slice.call(document.querySelectorAll(a))}catch(ga){}if(!b.elementsFormula)return e;a=function(a){var b=a.match(/^(-?\d*)n(\s*(?:\+|-)\s*\d+)?$/);
if(!b)return!1;a=b[1]||"1";a=isNaN(a)?"-1":a;b=b[2]||"0";return b=b.replace(/\s/g,""),[Number(a),Number(b)]}(b.elementsFormula);if(!a)return[];var c=a[0],d=a[1];return e.filter(function(a,b){return 0<=(++b-d)/c&&(b-d)/c%1==0})}(b,e);if(b.length){for(var k=0,g=0,w=b.length;g<w;g++)if(b[g].classList.remove("ramp-incontent-progressive"),!b[g].classList.contains("ramp-incontent"))if(k++,!e.progressive||k<=e.progressive){if(b[g].classList.add("ramp-incontent"),!d||k<=d){if(0===g){var h=document.getElementById(a)||
document.createElement("div");h.id=a,c(h,b[g],e.position)}else{var h="".concat(a,"-").concat(g).concat((new Date).getTime()),H=document.createElement("div");H.id=h,H.classList.add("purchrtb-dynamic"),c(H,b[g],e.position),f.push(h)}k===e.progressive-1&&b[g].classList.add("ramp-incontent-progressive")}}else b[g].classList.add("ramp-incontent-progressive");e.clone&&window.tmntag.adunitClone(a,f,null,{disableRefreshRamp:0,resetPosition:1})}return fa(a),0<b.length};var Y=!1;window.tmntag_onAdTagReady=
function(){if(Y);else{{Y=1;for(var a=document.querySelectorAll(".purchrtb-dynamic"),b={},e=0,c=a.length;e<c;e++){var d=a[e].id.lastIndexOf("-");if(0<d){d=a[e].id.substring(0,d);b[d]||(b[d]=[]),b[d].push(a[e].id)}a[e].className=a[e].className.replace("purchrtb-dynamic","")}for(var f in b)window.tmntag.adunitClone(f,b[f],null,{disableRefreshRamp:!1})}}},window.tmntag.cmd.executeCommands=function(){for(var a;a=window.tmntag.cmd.shift();)"function"==typeof a&&a()},window.tmntag.cmd.push=function(a){window.tmntag.cmd.executeCommands(),
"function"==typeof a&&a()},window.tmntag.cmd.pushDefined=!0;C=function k(){window.tmntag.cmd.pushDefined?window.tmntag.cmd.executeCommands():setTimeout(k,100)};C(),window.tmntag.apiReady=!0,window.tmntag.timing.endHead=(new Date).getTime(),window.tmntag.timing.debug=function(a){var b={timing:{}};if(a&&window.tmntag.timing){a=window.tmntag.timing;b.timing.ramp={},b.timing.ramp.head=a.endHead-a.start,b.timing.ramp.loadTag=a.loadTag-a.start,b.timing.ramp.startTag=a.startTag-a.loadTag,b.timing.ramp.googleEnableServices=
a.endEnableServices-a.startEnableServices,b.timing.ramp.endTag=a.endTag-a.startTag,b.timing.ramp.total=a.endTag-a.start}if(window.performance){a=window.performance.timing;b.timing.ttfb=a.responseStart-a.requestStart,b.timing.ttlb=a.responseEnd-a.responseStart,b.timing.ttsr=a.domInteractive-a.responseEnd}return b},window.tmntag.debug=function(){var a={};if(a.TMNAPI_VERSION=window.TMNAPI_VERSION,a.PREBID_TIMEOUT=window.PREBID_TIMEOUT,a.TMNTAG_VERSION=window.TMNTAG_VERSION,a.timing=window.tmntag.timing.debug(),
a.googletag="undefined"!=typeof googletag?window.googletag:"none",a.initialLoadEnabled=window.tmntag_initialLoadDisabled,a.singleRequestEnabled=window.tmntag.sr,a.collapseEmptyDivs=window.tmntag.ced,a.tmntag=window.tmntag,a.tmntagCache=window.tmntagCache,a.tmntagDisplayed=window.tmntagDisplayed,a.adunits=window.tmntag.a,a.googleSlots=window.tmntag.slots,a.pageLoation=window.tmntag_topLocation(),a.now=window.tmntag.t,a.timeZone=window.tmntag.tz,a.browserDim=window.tmntag.r,a.adParameters=window.tmntag.adparams,
a.placement=window.tmntag.p,a.amazonAds="undefined"!=typeof amznads?window.amznads:"none",a.prebidSlots="undefined"!=typeof prebidSlots?window.prebidSlots:"none",a.prebidAds="undefined"!=typeof prebidAds?window.prebidAds:"none",a.target=void 0!==window.tmntag.pubtargets?window.tmntag.pubtargets:"none",a.adunitTarget=void 0!==window.tmntag.adtargets?window.tmntag.adtargets:"none",a.adMarkups=void 0!==window.tmntag.markups?window.tmntag.markups:"none",window.googletag){var b=window.googletag.pubads().getSlots().map(function(a){a=
a.getSlotElementId();return document.getElementById(a)?{Message:"Checked",DIV:a,Type:"GOOD"}:{Message:"Ad Slot declared in GPT, but NO DIV found on page",DIV:a,Type:"BAD !"}});console.table&&console.table(b),a.tagchecks=b}return a},window.tmntag.isMobile=function(){var a,b=!1;return a=navigator.userAgent||navigator.vendor||window.opera,(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a)||
/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4)))&&(b=!0),b},window.tmntag_waitForCMP=m.e,window.tmntag.executeWithGDPRConsent=m.a,window.userSyncPixels=new d.a,window.purch_history=function(a){a.pvLoggingDisabled=!0,a.pageHistory={},a.pageHistory[window.location.pathname]=1;!function(a){var b=a.replaceState;a.replaceState=function(e,c,d){return"function"==typeof a.onreplacestate&&window.location.pathname!==d&&a.onreplacestate(e,c,d),b.apply(a,arguments)};var e=a.pushState;a.pushState=function(b,c,d){return"function"==typeof a.onpushstate&&
window.location.pathname!==d&&a.onpushstate(b,c,d),e.apply(a,arguments)}}(window.history),history.onreplacestate=history.onpushstate=function(b,c,d){if(a.onPageChangedDisabled);else{{b=d;a.pageHistory[b]||(a.pageHistory[b]=1,window.purch_history_onNewPage(b))}}},window.purch_history_onNewPage=function(b){if(!a.pvLoggingDisabled){b={};a.pubtargets&&(b=Object(n.b)(a.pubtargets,["_ex","_rid"],b)),window.tmntag_triggerEvent("PV",{id:b._rid,e:b._ex,l:encodeURIComponent(window.tmntag_topLocation())})}}},
window.purch_history(window.tmntag),window.tmntag.events=y.a,window.tmntag.inView=K.a,window.tmntag.autorefresh=g.a,window.tmntag_processTmntagResponse=window.tmntag.processTmntagResponse=function(){if(window.TMNTAG_READY=1,void 0!==window.tmntag.pubtargets&&window.tmntag.pubtargets){window.experimentId&&window.tmntag.pubtargets.push(["_experiment",window.experimentId]);var a=R();0<a.indexOf("google")?window.tmntag.pubtargets.push(["_ts","gs"]):0<a.indexOf("yahoo")?window.tmntag.pubtargets.push(["_ts",
"ys"]):0<a.indexOf("bing")&&window.tmntag.pubtargets.push(["_ts","bs"])}window.tmntag.timing&&(window.tmntag.timing.startTag=(new Date).getTime()),"undefined"!=typeof googletag&&window.googletag.cmd.push(function(){if(window.tmntag&&window.tmntag.isNonPersonalizedAds&&window.googletag.pubads().setRequestNonPersonalizedAds(1),"function"==typeof tmntag_defineSlot&&"undefined"!=typeof tmntag&&void 0!==window.tmntag.a)if(window.tmntag&&1===window.tmntag.f){if(window.tmntag.adtargets)for(var a in window.tmntag.adtargets)window.tmntag.adtargets.hasOwnProperty(a)&&
window.tmntag_defineAdUnit(a)}else for(a=0;a<window.tmntag.a.length;a++){var b=window.tmntag.a[a].d;window.tmntag_defineAdUnit(b)}else window.tmntag_defineSlots();if("undefined"!=typeof tmntag&&void 0!==window.tmntag.pubtargets)for(a=0;a<window.tmntag.pubtargets.length;a++)window.googletag.pubads().setTargeting(window.tmntag.pubtargets[a][0],window.tmntag.pubtargets[a][1]);if(Object(z.b)()&&Object(z.c)(),"undefined"!=typeof tmntag&&void 0!==window.tmntag.su&&1===window.tmntag.su&&void 0!==window.tmntag.l&&
window.googletag.pubads().set("page_url",decodeURIComponent(window.tmntag.l)),1!==window.tmntag.f&&"undefined"!=typeof tmntag&&void 0!==window.tmntag.sr&&!0===window.tmntag.sr&&window.googletag.pubads().enableSingleRequest(),1!==window.tmntag.f&&"undefined"!=typeof tmntag&&void 0!==window.tmntag_il&&!1===window.tmntag_il&&(console.log("- RAMP - DISABLE INITIAL LOAD"),window.googletag.pubads().disableInitialLoad()),1!==window.tmntag.f&&"undefined"!=typeof tmntag&&void 0!==window.tmntag.ced&&!0===window.tmntag.ced&&
window.googletag.pubads().collapseEmptyDivs(),1!==window.tmntag.f){for(var c in window.tmntag.timing&&(window.tmntag.timing.startEnableServices=(new Date).getTime()),"function"===window.tmntag.instartlogicEnabled&&window.tmntag.instartlogicEnabled()||window.googletag.enableServices(),w(),window.tmntag_callbacks.executeCallbacks(),window.tmntag.timing&&(window.tmntag.timing.endEnableServices=(new Date).getTime()),window.tmntag.slots)(a=document.getElementById(c))&&void 0!==a&&window.tmntagDisplayed&&
1===window.tmntagDisplayed[c]&&window.googletag.display(c);"undefined"==typeof tmntag||void 0===window.tmntag_il||!1!==window.tmntag_il||window.disable_refresh||(console.log("- RAMP - REFRESH"),window.googletag.pubads().refresh())}"function"==typeof window.tmntag_onAdTagReady&&window.tmntag_onAdTagReady()}),window.tmntag.timing&&(window.tmntag.timing.endTag=(new Date).getTime())}},function(d,g){d.exports=function(a){if(Array.isArray(a)){for(var b=0,d=new Array(a.length);b<a.length;b++)d[b]=a[b];return d}}},
function(d,g){d.exports=function(a){if(Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a))return Array.from(a)}},function(d,g){d.exports=function(){throw new TypeError("Invalid attempt to spread non-iterable instance");}},function(d,g,a){d=function(a){function b(a,b,c,f){b=b&&b.prototype instanceof g?b:g;b=Object.create(b.prototype);f=new K(f||[]);return b._invoke=function(a,b,c){var f=N;return function(g,h){if(f===E)throw new Error("Generator is already running");
if(f===O){if("throw"===g)throw h;return D()}for(c.method=g,c.arg=h;;){if(g=c.delegate)if(g=l(g,c)){if(g===B)continue;return g}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(f===N)throw f=O,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);f=E;g=d(a,b,c);if("normal"===g.type){if(f=c.done?O:v,g.arg===B)continue;return{value:g.arg,done:c.done}}"throw"===g.type&&(f=O,c.method="throw",c.arg=g.arg)}}}(a,c,f),b}function d(a,b,c){try{return{type:"normal",
arg:a.call(b,c)}}catch(R){return{type:"throw",arg:R}}}function g(){}function m(){}function h(){}function q(a){["next","throw","return"].forEach(function(b){a[b]=function(a){return this._invoke(b,a)}})}function t(a){var b;this._invoke=function(c,f){function g(){return new Promise(function(b,g){!function Q(b,c,f,g){b=d(a[b],a,c);if("throw"!==b.type){var h=b.arg;return(b=h.value)&&"object"==typeof b&&F.call(b,"__await")?Promise.resolve(b.__await).then(function(a){Q("next",a,f,g)},function(a){Q("throw",
a,f,g)}):Promise.resolve(b).then(function(a){h.value=a,f(h)},function(a){return Q("throw",a,f,g)})}g(b.arg)}(c,f,b,g)})}return b=b?b.then(g,g):g()}}function l(a,b){var c=a.iterator[b.method];if(c===z){if(b.delegate=null,"throw"===b.method){if(a.iterator.return&&(b.method="return",b.arg=z,l(a,b),"throw"===b.method))return B;b.method="throw",b.arg=new TypeError("The iterator does not provide a 'throw' method")}return B}c=d(c,a.iterator,b.arg);if("throw"===c.type)return b.method="throw",b.arg=c.arg,
b.delegate=null,B;return(c=c.arg)?c.done?(b[a.resultName]=c.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=z),b.delegate=null,B):c:(b.method="throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,B)}function c(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]),2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]),this.tryEntries.push(b)}function n(a){var b=a.completion||{};b.type="normal",delete b.arg,a.completion=b}function K(a){this.tryEntries=[{tryLoc:"root"}],
a.forEach(c,this),this.reset(!0)}function y(a){if(a){var b=a[C];if(b)return b.call(a);if("function"==typeof a.next)return a;if(!isNaN(a.length)){var c=-1,b=function A(){for(;++c<a.length;)if(F.call(a,c))return A.value=a[c],A.done=!1,A;return A.value=z,A.done=!0,A};return b.next=b}}return{next:D}}function D(){return{value:z,done:!0}}var z,M=Object.prototype,F=M.hasOwnProperty,x="function"==typeof Symbol?Symbol:{},C=x.iterator||"@@iterator",L=x.asyncIterator||"@@asyncIterator",G=x.toStringTag||"@@toStringTag";
a.wrap=b;var N="suspendedStart",v="suspendedYield",E="executing",O="completed",B={},x={};x[C]=function(){return this};var I=Object.getPrototypeOf;(I=I&&I(I(y([]))))&&I!==M&&F.call(I,C)&&(x=I);var J=h.prototype=g.prototype=Object.create(x);return m.prototype=J.constructor=h,h.constructor=m,h[G]=m.displayName="GeneratorFunction",a.isGeneratorFunction=function(a){a="function"==typeof a&&a.constructor;return!!a&&(a===m||"GeneratorFunction"===(a.displayName||a.name))},a.mark=function(a){return Object.setPrototypeOf?
Object.setPrototypeOf(a,h):(a.__proto__=h,G in a||(a[G]="GeneratorFunction")),a.prototype=Object.create(J),a},a.awrap=function(a){return{__await:a}},q(t.prototype),t.prototype[L]=function(){return this},a.AsyncIterator=t,a.async=function(c,d,f,g){var h=new t(b(c,d,f,g));return a.isGeneratorFunction(d)?h:h.next().then(function(a){return a.done?a.value:h.next()})},q(J),J[G]="Generator",J[C]=function(){return this},J.toString=function(){return"[object Generator]"},a.keys=function(a){var b=[],c;for(c in a)b.push(c);
return b.reverse(),function A(){for(;b.length;){var c=b.pop();if(c in a)return A.value=c,A.done=!1,A}return A.done=!0,A}},a.values=y,K.prototype={constructor:K,reset:function(a){if(this.prev=0,this.next=0,this.sent=this._sent=z,this.done=!1,this.delegate=null,this.method="next",this.arg=z,this.tryEntries.forEach(n),!a)for(var b in this)"t"===b.charAt(0)&&F.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=z)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;
return this.rval},dispatchException:function(a){function b(b,d){return g.type="throw",g.arg=a,c.next=b,d&&(c.method="next",c.arg=z),!!d}if(this.done)throw a;for(var c=this,d=this.tryEntries.length-1;0<=d;--d){var f=this.tryEntries[d],g=f.completion;if("root"===f.tryLoc)return b("end");if(f.tryLoc<=this.prev){var h=F.call(f,"catchLoc"),l=F.call(f,"finallyLoc");if(h&&l){if(this.prev<f.catchLoc)return b(f.catchLoc,!0);if(this.prev<f.finallyLoc)return b(f.finallyLoc)}else if(h){if(this.prev<f.catchLoc)return b(f.catchLoc,
!0)}else{if(!l)throw new Error("try statement without catch or finally");if(this.prev<f.finallyLoc)return b(f.finallyLoc)}}}},abrupt:function(a,b){for(var c=this.tryEntries.length-1;0<=c;--c){var d=this.tryEntries[c];if(d.tryLoc<=this.prev&&F.call(d,"finallyLoc")&&this.prev<d.finallyLoc){var f=d;break}}f&&("break"===a||"continue"===a)&&f.tryLoc<=b&&b<=f.finallyLoc&&(f=null);c=f?f.completion:{};return c.type=a,c.arg=b,f?(this.method="next",this.next=f.finallyLoc,B):this.complete(c)},complete:function(a,
b){if("throw"===a.type)throw a.arg;return"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&b&&(this.next=b),B},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),n(c),B}},catch:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===
a.type){var d=a.arg;n(c)}return d}}throw new Error("illegal catch attempt");},delegateYield:function(a,b,c){return this.delegate={iterator:y(a),resultName:b,nextLoc:c},"next"===this.method&&(this.arg=z),B}},a}(d.exports);try{regeneratorRuntime=d}catch(b){Function("r","regeneratorRuntime = r")(d)}},function(d,g){String.prototype.endsWith||(String.prototype.endsWith=function(a,b){return(void 0===b||b>this.length)&&(b=this.length),this.substring(b-a.length,b)===a}),String.prototype.startsWith||(String.prototype.startsWith=
function(a,b){return b=b||0,this.substr(b,a.length)===a}),Array.prototype.find||Object.defineProperty(Array.prototype,"find",{value:function(a,b){if(null==this)throw new TypeError('"this" is null or not defined');var d=Object(this),g=d.length>>>0;if("function"!=typeof a)throw new TypeError("predicate must be a function");b=b;for(var r=0;r<g;){var m=d[r];if(a.call(b,m,r,d))return m;r++}}}),"remove"in Element.prototype||(Element.prototype.remove=function(){this.parentNode&&this.parentNode.removeChild(this)}),
"function"!=typeof Object.assign&&Object.defineProperty(Object,"assign",{value:function(a,b){if(null==a)throw new TypeError("Cannot convert undefined or null to object");for(var d=Object(a),g=1;g<arguments.length;g++){var r=arguments[g];if(null!=r)for(var m in r)Object.prototype.hasOwnProperty.call(r,m)&&(d[m]=r[m])}return d},writable:!0,configurable:!0})}]));
tmntag.floorprices={};
tmntag.headerbidderstodrop={};try {
tmntag_ready(function() {

userSyncPixels._fragment=document.createElement("div");

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=185;userSyncPixels.create(11,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("script");a.type="text/javascript";a.async=true;a.src="//bttrack.com/pixel/cookiesync?source=cfc80ad2-7c39-4243-92d6-3ecc1b9a38c6&secure=1";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=32;userSyncPixels.create("23_26_29_33",iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var c=Math.floor(Math.random()*11E3),a=document.createElement("img");a.style.display="none";var b=document.location.protocol==="https:"?"https":"http";a.src=b+"://ib.adnxs.com/getuid?"+b+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D23%2C26%2C29%26uid%3D$UID";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

function requestToken(){var a=document.getElementById(frameId);a.contentWindow.postMessage("GET_FB_TOKEN_198782813737","https://www.facebook.com")}function receiveFBToken(a){if(a.origin.indexOf("https://www.facebook.com")!==-1){var b="; expires="+a.data.expAfter;a=JSON.parse(a.data);document.cookie="up_28="+encodeURIComponent(a.fbToken)+b+"; path=/"}}
if(!window.gdprUser&&document.location.host.indexOf("creativebloq.com")<=0){var frameId="fb_iframe";if(typeof window.INSTART==="undefined"){try{var fbIframe=document.createElement("iframe");fbIframe.id=frameId;fbIframe.width="0";fbIframe.height="0";fbIframe.frameBorder="0";fbIframe.src="https://www.facebook.com/audiencenetwork/token/v1/";document.body.appendChild(fbIframe);fbIframe.onload=function(){requestToken()}}catch(a){console.error(a)}window.addEventListener("message",receiveFBToken,false)}};

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=undefined;
userSyncPixels.create("51_52_53_54",iabId,"guitarworld.com|loudersound.com|creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var b=document.createElement("span"),c=Math.floor(Math.random()*11E3);b.style.display="none";var d=document.location.protocol==="https:"?"https":"http",a=document.createElement("iframe");a.style.display="none";a.src="//sync.mathtag.com/sync/img?mt_exid=66&redir="+encodeURIComponent(d+"://pixel.servebom.com/partner?cb="+c+"&svc=us&id=51%2C52%2C53%2C54&uid=[MM_UUID]");b.appendChild(a);
userSyncPixels._fragment.appendChild(b);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=69;
userSyncPixels.create("22",iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var b=document.createElement("span"),c=Math.floor(Math.random()*11E3);b.style.display="none";var d=document.location.protocol==="https:"?"https":"http",a=document.createElement("iframe");a.style.display="none";a.src="//us-u.openx.net/w/1.0/cm?id=de2d90e5-4d26-4c8c-a342-3edcde51fdb1&ph=25af9286-f23b-4b02-abcd-f2ee3b564dab&r="+d+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcd%3D"+c+"%26svc%3Dus%26id%3D22%26uid%3D";b.appendChild(a);
userSyncPixels._fragment.appendChild(b);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=104;
userSyncPixels.create(9,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){if(window.gdprUser)return;try{var c=document.createElement("script");c.src="//sync.go.sonobi.com/uc.js";userSyncPixels._fragment.appendChild(c)}catch(a){console.error(a)}try{var e=Math.floor(Math.random()*11E3),b=document.createElement("img"),d=document.location.protocol==="https:"?"https":"http";b.src=d+"://purch-sync.go.sonobi.com/us?"+d+"://pixel.servebom.com/partner?cb="+e+"&svc=us&id=9&uid=[UID]";userSyncPixels._fragment.appendChild(b);
return b}catch(a){console.error(a)}});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=13;userSyncPixels.create(24,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),c=Math.floor(Math.random()*11E3);a.style.display="none";var b=document.location.protocol==="http:"?"http":"https";a.defer=true;a.src=b+"://ap.lijit.com/pixel?redir="+b+":%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D24%26uid%3D$UID";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=28;userSyncPixels.create(14,iabId,"buyerzone.com|newegg.com|businessnewsdaily.com",false,function(){var b=document.createElement("span"),c=Math.floor(Math.random()*11E3);b.style.display="none";var a=document.createElement("iframe");a.style.display="none";a.src="//eb2.3lift.com/getuid?redir=%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D14%26uid%3D%24UID";b.appendChild(a);userSyncPixels._fragment.appendChild(b);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=76;userSyncPixels.create(5,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("script");a.async=true;a.type="text/javascript";a.src="https://ads.pubmatic.com/AdServer/js/userSync.js";a.onload=function(){PubMaticSync.sync({pubId:46338,delay:1E3,url:"https://pixel.servebom.com/partner?svc=us&id=5&cb="+Math.floor(Math.random()*11E3)+"&uid=(PM_UID)",macro:"(PM_UID)"})};userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=24;userSyncPixels.create(36,iabId,"guitarworld.com|loudersound.com|creativebloq.com|buyerzone.com|newegg.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),c=Math.floor(Math.random()*11E3);a.style.display="none";var b=document.location.protocol==="http:"?"http":"https";a.defer=true;a.src=b+"://purch-match.dotomi.com/match/bounce/current?networkId=20077&version=1&rurl="+b+":%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D36%26uid%3D$UID";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=76;userSyncPixels.create(45,iabId,"creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("script");a.async=true;a.type="text/javascript";a.src="https://ads.pubmatic.com/AdServer/js/userSync.js";a.onload=function(){PubMaticSync.sync({pubId:155494,delay:1E3,url:"https://pixel.servebom.com/partner?svc=us&id=45&cb="+Math.floor(Math.random()*11E3)+"&uid=(PM_UID)",macro:"(PM_UID)"})};userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=202;
userSyncPixels.create(32,iabId,"space.com|tomsguide.com|tomshardware.com|livescience.com|laptopmag.com|newsarama.com|imore.com|androidcentral.com|windowscentral.com",true,function(){var c="pixel.servebom.com",a=Math.floor(Math.random()*11E3),f="tmx_sync_"+a,b="qds0l";if(b===""||b.indexOf("$")===0)return;var d=document.createElement("span");d.style.display="none";var e=document.location.protocol==="http:"?"http":"https",b=b+".publishers.tremorhub.com",c=e+"://"+b+"/pubsync?redir="+e+":%2F%2F"+c+"%2Fpartner%3Fcb%3D"+a+"%26svc%3Dus%26id%3D32%26uid%3D%5Btvid%5D",a=document.createElement("iframe");a.id=
a.name=f;a.src=c;a.frameBorder=0;a.frameSpacing=0;a.scrolling="no";a.width=1;a.height=1;d.appendChild(a);userSyncPixels._fragment.appendChild(d);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=81;
userSyncPixels.create(17,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var c=document.location.protocol==="https:"?"https":"http",b=document.createElement("span"),d=Math.floor(Math.random()*11E3);b.style.display="none";var a=document.createElement("iframe");a.style.display="none";a.src=c+"://bh.contextweb.com/bh/rtset?pid=558527&cb="+d+"&ev=1&rurl="+c+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fsvc%3Dus%26id%3D17%26cb%3D"+d+"%26uid%3D%25%25VGUID%25%25";b.appendChild(a);userSyncPixels._fragment.appendChild(b);
return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=10;
userSyncPixels.create(2,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),b=Math.floor(Math.random()*11E3);a.style.display="none";var c=document.location.protocol;a.defer=true;var d="ssum.casalemedia.com";if(document.location.protocol==="https:")d="ssum-sec.casalemedia.com";a.src=c+"//"+d+"/usermatch?r="+b+"&s=181869&cb="+c+"%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+b+"%26svc%3Dus%26id%3D2%26uid%3D";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=335;userSyncPixels.create(42,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;if(window.gdprUser&&window.__cmp)__cmp("getVendorConsents",null,function(b){a.src="https://sync.bfmio.com/sync_iframe?ifpl=5&ifg=4&id=Purch&gdpr=1&gc="+b.metadata+"&gce=1";userSyncPixels._fragment.appendChild(a)});else{a.src="https://sync.bfmio.com/sync_iframe?ifpl=5&ifg=4&id=Purch&gdpr=0&gc=&gce=1";userSyncPixels._fragment.appendChild(a)}return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=undefined;userSyncPixels.create(15,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),c=Math.floor(Math.random()*11E3);a.style.display="none";var b=document.location.protocol;a.async=true;a.src=b+"//sync.adkernel.com/user-sync?zone=39660&r="+b+"%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D15%26uid%3D{UID}";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=76;
userSyncPixels.create(46,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var b=document.createElement("span"),c=Math.floor(Math.random()*11E3);b.style.display="none";var d=document.location.protocol==="https:"?"https":"http",a=document.createElement("iframe");a.style.display="none";a.src="//ads.pubmatic.com/AdServer/js/user_sync.html?r="+c+"&p=156007&predirect="+d+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcd%3D"+c+"%26svc%3Dus%26id%3D46%26uid%3D";b.appendChild(a);userSyncPixels._fragment.appendChild(b);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var partnerId=27,iabId=236;userSyncPixels.create(partnerId,iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;a.src="https://px.powerlinks.com/user/identify?rurl=https%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fsvc%3Dus%26id%3D"+partnerId+"%26uid%3D${USER}";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=52;userSyncPixels.create("19",iabId,"",false,function(){var c=Math.floor(Math.random()*11E3),a=document.createElement("iframe");a.style.display="none";a.async=true;var b="assets.rubiconproject.com";if(document.location.protocol==="https:")b="secure-assets.rubiconproject.com";var d="11868",e="us-east";a.src=document.location.protocol+"//"+b+"/utils/xapi/multi-sync.html?r="+c+"&p="+d+"&endpoint="+e;userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var partnerId=55,iabId=184;userSyncPixels.create(partnerId,iabId,"guitarworld.com|loudersound.com|creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;a.src="https://cookie-matching.mediarithmics.com/v1/get_user_agent_id?dom_token=purch18";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var partnerId=57,iabId=25;
userSyncPixels.create(partnerId,iabId,"guitarworld.com|loudersound.com|creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;if(window.gdprUser&&window.__cmp)__cmp("getVendorConsents",null,function(b){a.src="https://pixel.advertising.com/ups/58164/sync?gdpr=1&gdpr_consent="+b.metadata+"&_origin=1&redir=true";userSyncPixels._fragment.appendChild(a)});else{a.src="https://pixel.advertising.com/ups/58164/sync?gdpr=0&gdpr_consent=&_origin=1&redir=true";userSyncPixels._fragment.appendChild(a)}});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=183;userSyncPixels.create("25",iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var c=Math.floor(Math.random()*11E3),a=document.createElement("img");a.style.display="none";var b=document.location.protocol==="https:"?"https":"http";a.src=b+"://cs.emxdgt.com/um?redirect="+b+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D25%26uid%3D$UID";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=36;userSyncPixels.create("58",iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var b=Math.floor(Math.random()*11E3),a=document.createElement("img");a.style.display="none";var c=document.location.protocol==="https:"?"https":"http";a.src=c+"://sync.1rx.io/usersync2/rmpssp?sub=purch&redir=https%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+b+"%26svc%3Dus%26id%3D58%26uid%3D%5BRX_UUID%5D";userSyncPixels._fragment.appendChild(a);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var iabId=58;
userSyncPixels.create("59",iabId,"buyerzone.com|businessnewsdaily.com",false,function(){var b=document.createElement("span"),c=Math.floor(Math.random()*11E3);b.style.display="none";var d=document.location.protocol==="https:"?"https":"http",a=document.createElement("iframe");a.style.display="none";a.src="//pixel.33across.com/ps?m=xch&rt=html&id=0013300001kQj3GAAS&ru="+encodeURIComponent(d+"://pixel.servebom.com/partner?cb="+c+"&svc=us&id=59&uid=33XUSERID33X");b.appendChild(a);userSyncPixels._fragment.appendChild(b);return a});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

(function(){document.body.appendChild(userSyncPixels._fragment)})();

});
} catch (e) {
console.error(e);
}
